from django.core.management.base import BaseCommand
from django.db import transaction
from apps.diccionario.models import Categoria, Palabra

class Command(BaseCommand):
    help = 'Carga palabras específicamente para mini juegos con descripciones especiales'

    def add_arguments(self, parser):
        parser.add_argument(
            '--limpiar-juegos',
            action='store_true',
            help='Elimina todas las palabras de juegos existentes antes de cargar',
        )
        parser.add_argument(
            '--solo-kichwa-espanol',
            action='store_true',
            help='Carga solo las palabras kichwa-español para juegos',
        )
        parser.add_argument(
            '--solo-espanol-kichwa',
            action='store_true',
            help='Carga solo las palabras español-kichwa para juegos',
        )

    def handle(self, *args, **options):
        if options['limpiar_juegos']:
            self.stdout.write('Eliminando palabras de juegos existentes...')
            Palabra.objects.filter(apta_para_juegos=True).delete()

        # Crear categorías específicas para juegos
        self.crear_categorias_juegos()
        
        # Cargar según las opciones
        if options['solo_kichwa_espanol']:
            self.cargar_palabras_juegos_kichwa_espanol()
        elif options['solo_espanol_kichwa']:
            self.cargar_palabras_juegos_espanol_kichwa()
        else:
            # Cargar ambos tipos
            self.cargar_palabras_juegos_kichwa_espanol()
            self.cargar_palabras_juegos_espanol_kichwa()
        
        total_palabras_juegos = Palabra.objects.filter(apta_para_juegos=True).count()
        self.stdout.write(
            self.style.SUCCESS(f'¡Carga de juegos completada! Total de palabras para juegos: {total_palabras_juegos}')
        )

    def crear_categorias_juegos(self):
        """Crea categorías específicas para juegos"""
        categorias_juegos = [
            {'nombre': 'Juegos Básicos', 'descripcion': 'Palabras básicas para juegos principiantes', 'color': '#00D2D3'},
            {'nombre': 'Juegos Intermedios', 'descripcion': 'Palabras de nivel intermedio para juegos', 'color': '#FF6B6B'},
            {'nombre': 'Juegos Avanzados', 'descripcion': 'Palabras avanzadas para juegos expertos', 'color': '#4ECDC4'},
            {'nombre': 'Memoria Rápida', 'descripcion': 'Palabras cortas para juegos de memoria', 'color': '#45B7D1'},
            {'nombre': 'Traducción Directa', 'descripcion': 'Palabras para ejercicios de traducción', 'color': '#96CEB4'},
        ]
        
        for cat_data in categorias_juegos:
            categoria, created = Categoria.objects.get_or_create(
                nombre=cat_data['nombre'],
                defaults=cat_data
            )
            if created:
                self.stdout.write(f'Categoría de juegos creada: {categoria.nombre}')

    def determinar_categoria_juego(self, palabra_kichwa, traduccion_espanol, descripcion):
        """Determina la categoría más apropiada para una palabra de juego"""
        palabra_lower = palabra_kichwa.lower()
        traduccion_lower = traduccion_espanol.lower()
        descripcion_lower = descripcion.lower() if descripcion else ''
        
        # Palabras cortas para memoria rápida
        if len(palabra_kichwa) <= 4 or len(traduccion_espanol) <= 4:
            return 'Memoria Rápida'
        
        # Palabras complejas para nivel avanzado
        if len(palabra_kichwa) > 10 or len(traduccion_espanol) > 10:
            return 'Juegos Avanzados'
        
        # Palabras con descripciones largas para traducción
        if len(descripcion) > 50:
            return 'Traducción Directa'
        
        # Palabras de longitud media para nivel intermedio
        if 5 <= len(palabra_kichwa) <= 8:
            return 'Juegos Intermedios'
        
        # Por defecto, básico
        return 'Juegos Básicos'

    def determinar_dificultad_juego(self, palabra_kichwa, traduccion_espanol, descripcion):
        """Determina la dificultad de la palabra para juegos"""
        # Palabras muy cortas = fácil
        if len(palabra_kichwa) <= 4 and len(traduccion_espanol) <= 5:
            return 'facil'
        
        # Palabras muy largas o con descripciones complejas = difícil
        if len(palabra_kichwa) > 10 or len(traduccion_espanol) > 12 or len(descripcion) > 100:
            return 'dificil'
        
        # Resto = medio
        return 'medio'

    @transaction.atomic
    def cargar_palabras_juegos_kichwa_espanol(self):
        """Carga las 751 palabras kichwa-español para juegos"""
        self.stdout.write('Cargando palabras kichwa-español para juegos...')
        
        # ============================================
        # COPIA Y PEGA AQUÍ TUS 751 PALABRAS KICHWA-ESPAÑOL PARA JUEGOS
        # Formato: ('término_kichwa', 'descripción_en_español'),
        # ============================================
        palabras_juegos_kichwa_espanol = [
            ('achikyana', 'brillar'),
            ('achikyaya', 'padrino'),
            ('achillik-yaya', 'dios'),
            ('achira', 'achera'),
            ('achukcha', 'achogcha'),
            ('achupalla', 'achupalla'),
            ('akirinri', 'jengibre'),
            ('aklluna', 'tartamudear'),
            ('aknina', 'eructar'),
            ('aktuna', 'escupir'),
            ('akuna', 'masticar'),
            ('akwas', 'sarna'),
            ('ala', 'hongo'),
            ('alapana', 'rematar'),
            ('allku', 'perro'),
            ('allu', 'moho'),
            ('ama', 'no'),
            ('amarak', 'todavía'),
            ('amaru', 'boa'),
            ('aminta', 'insípido'),
            ('ampana', 'bostezar'),
            ('ana', 'lunar'),
            ('anak', 'duro'),
            ('ananas', 'chirimoya'),
            ('ankas', 'azul'),
            ('ansa', 'poco'),
            ('añanku', 'hormiga'),
            ('añañay', 'hermoso'),
            ('añas', 'zorrillo'),
            ('apachi', 'carga'),
            ('apamuna', 'traer'),
            ('apankura', 'cangrejo'),
            ('apapa', 'búho'),
            ('apay', 'paquete'),
            ('apana', 'llevar'),
            ('apichu', 'camote'),
            ('apiw', 'caballo'),
            ('apiyana', 'suavizarse'),
            ('ari', 'si'),
            ('armana', 'bañar'),
            ('asha', 'poco'),
            ('ashalla', 'poquito'),
            ('ashi', 'amante'),
            ('ashnana', 'oler'),
            ('asichik', 'bromista'),
            ('asina', 'reir'),
            ('aspi', 'raya'),
            ('aswa', 'chicha'),
            ('ataku', 'sangorache'),
            ('atallpa', 'gallina'),
            ('atatay', 'asco'),
            ('atina', 'vencer'),
            ('atsikyana', 'estornudar'),
            ('atuk', 'lobo'),
            ('atupa', 'maíz'),
            ('atyak', 'babosa'),
            ('awanakaspi', 'telar'),
            ('awasi', 'inepto'),
            ('awana', 'tejer'),
            ('awinchina', 'resembrar'),
            ('awllina', 'urdir'),
            ('aya', 'cadáver'),
            ('ayar', 'noviembre'),
            ('aycha', 'carne'),
            ('ayki', 'estafa'),
            ('aykina', 'estafar'),
            ('ayri', 'hacha'),
            ('ayriwa', 'abril'),

            # Sección CH - Palabras que empiezan con 'ch'
            ('chaka', 'puente'),
            ('chakana', 'camilla'),
            ('chakata', 'cruz'),
            ('chakka', 'raposa'),
            ('chakuk', 'cazador'),
            ('chani', 'precio'),
            ('chanka', 'pierna'),
            ('chapul', 'mariposa'),
            ('champira', 'chambira'),
            ('champuru', 'chamburo'),
            ('chamuk', 'soso'),
            ('chanchana', 'entabillar'),
            ('charapa', 'tortuga'),
            ('charina', 'mancera'),
            ('charki', 'cecina'),
            ('chas', 'brote'),
            ('chaska', 'Venus'),
            ('chaski', 'mensajero'),
            ('chaspina', 'sacudir'),
            ('chasu', 'aculturado'),
            ('chawa', 'crudo'),
            ('chawpi', 'mitad'),
            ('chayamuna', 'llegar'),
            ('chakri', 'herida'),
            ('chinta', 'chamisa'),
            ('chimpi', 'verruga'),
            ('chimpilaku', 'murciélago'),
            ('chinkana', 'casucha'),
            ('chinkillis', 'bilis'),
            ('chika', 'verdad'),
            ('chilina', 'naranja'),
            ('chilli', 'palmera'),
            ('chillik', 'langosta'),
            ('chimpu', 'Saturno'),
            ('china', 'hembra'),
            ('chini', 'hortiga'),
            ('chinkarina', 'perderse'),
            ('chinku', 'palmera'),
            ('chinta', 'chamisa'),
            ('chiri', 'frío'),
            ('chishi', 'tarde'),
            ('chita', 'chivo'),
            ('chiwilla', 'piña'),
            ('chiya', 'liendra'),
            ('chiyu', 'pájaro'),
            ('chimpana', 'cruzar'),
            ('chimpi', 'verruga'),
            ('chimpilaku', 'murciélago'),
            ('chinchay', 'norte'),
            ('chinkana', 'casucha'),
            ('chinkillis', 'bilis'),
            ('chucha', 'raposa'),
            ('chuki', 'arma'),
            ('chukirawa', 'chuquirahua'),
            ('chukllu', 'choco'),
            ('chukni', 'lagaña'),
            ('chakri', 'herida'),
            ('chulakyana', 'ampollarse'),
            ('chulla', 'impar'),
            ('chullanik', 'impar'),
            ('chullu', 'grillo'),
            ('chullumpi', 'miel'),
            ('chulunlla', 'silencioso'),
            ('chuna', 'escarabajo'),
            ('chunka', 'diez'),
            ('chunta', 'chonta'),
            ('chupu', 'tumor'),
            ('chura', 'ropa'),
            ('churi', 'hijo'),
            ('churu', 'caracol'),
            ('chushik', 'lechuza'),
            ('chusku', 'cuatro'),
            ('chuspi', 'mosco'),
            ('chusu', 'fruto'),
            ('chuwalli', 'gavilán'),
            ('chuya', 'limpio'),

            # Sección H - Palabras que empiezan con 'h'
            ('haku', 'vámonos'),
            ('hakuchik', 'vámonos'),
            ('hakuna', 'desmenuzar'),
            ('hallinka', 'collar'),
            ('hallkan', 'cucaracha'),
            ('halunzu', 'manta'),
            ('hamchi', 'afrecho'),
            ('hampara', 'mesa'),
            ('hampatu', 'sapo'),
            ('hampi', 'medicina'),
            ('hampina', 'curar'),
            ('harka', 'obstáculo'),
            ('harkashka', 'corral'),
            ('harnina', 'roncar'),
            ('hatun', 'inmenso'),
            ('hawalla', 'superficial'),
            ('haway', 'canción'),
            ('hawcha', 'verduras'),
            ('hawya', 'consuegra'),
            ('hay', 'expresión'),
            ('hayak', 'amargo'),
            ('hayampi', 'iguana'),
            ('hayka', '¿cuándo?'),
            ('hayri', 'minuto'),
            ('hiki', 'saltamontes'),
            ('hikiyana', 'sollozar'),
            ('hillu', 'goloso'),
            ('hipana', 'pujar'),
            ('huchanchina', 'culpar'),
            ('huka', 'huero'),
            ('hukana', 'desdesear'),
            ('hukipuna', 'silbar'),
            ('hukulluyana', 'ampollarse'),
            ('hulun', 'badea'),
            ('humpi', 'transpiración'),
            ('humpina', 'transpirar'),
            ('hunu', 'diez mil'),
            ('hupi', 'inútil'),
            ('huwin', 'sapo'),
           # Sección I - Palabras que empiezan con 'i'
            ('ichu', 'rápido'),
            ('ichuk', 'izquierdo'),
            ('ila', 'higuerón'),
            ('illak', 'cero'),
            ('illapa', 'escopeta'),
            ('ilta', 'guaba'),
            ('ima', '¿que?'),
            ('inchik', 'maní'),
            ('inka', 'emperador'),
            ('inku', 'carnero'),
            ('inti', 'sol'),
            ('intina', 'solear'),
            ('iñu', 'cosa'),
            ('ishkay', 'dos'),
            ('ishkuna', 'desgranar'),
            ('ishpana', 'orinar'),
            ('ishpapuru', 'vejiga'),
            ('ishpinku', 'canela'),
            ('isi', 'expresión'),
            ('iska', 'fósforo'),
            ('isku', 'cal'),
            ('ismana', 'defecar'),
            ('ismu', 'podrido'),
            ('itsipu', 'orzuelo'),
            ('iwa', 'tubérculo'),
            ('iwilan', 'arbusto'),

            # Sección K - Palabras que empiezan con 'k'
            ('kachi', 'sal'),
            ('kachun', 'nuera'),
            ('kalatis', 'bejuco'),
            ('kallampa', 'hongo'),
            ('kallana', 'tiesto'),
            ('kamachik', 'juez'),
            ('kamachina', 'acosejar'),
            ('kamachiy', 'ley'),
            ('kamari', 'regalo'),
            ('kamarina', 'regalar'),
            ('kamana', 'probar'),
            ('kamcha', 'tostado'),
            ('kamchana', 'tostar'),
            ('kamina', 'insultar'),
            ('kampik', 'cacao'),
            ('kan', 'tú'),
            ('kancha', 'cancha'),
            ('kanchis', 'siete'),
            ('kanichina', 'morder'),
            ('kanina', 'picar'),
            ('kankik', 'cadera'),
            ('kankil', 'canguil'),
            ('kantina', 'buscar'),
            ('kapuli', 'capulí'),
            ('kapya', 'frágil'),
            ('karacha', 'costra'),
            ('karachi', 'estopa'),
            ('karpa', 'toldo'),
            ('karu', 'lejos'),
            ('kasa', 'helada'),
            ('kasha', 'espina'),
            ('kashtuna', 'masticar'),
            ('kashuk', 'axila'),
            ('kasku', 'pecho'),
            ('kaspa', 'mazorca'),
            ('kaspi', 'palo'),
            ('kastilla', 'España'),
            ('katana', 'cobija'),
            ('katsu', 'escarabajo'),
            ('katu', 'colada'),
            ('katuna', 'vender'),
            ('kaw', 'choclo'),
            ('kawchuna', 'torcer'),
            ('kawchushka', 'torcido'),
            ('kawitu', 'cama'),
            ('kawpuna', 'torcer'),
            ('kawsay', 'vida'),
            ('kayllayana', 'acercarse'),
            ('kana', 'ser'),
            ('kay', 'este'),
            ('kaya', 'mañana'),
            ('kayana', 'llamar'),
            ('kayka', 'aquí'),
            ('kayna', 'ayer'),
            ('kaypi', 'aquí'),
            ('kazuk', 'quemado'),
            ('kicha', 'diarrea'),
            ('kichuna', 'quitar'),
            ('kila', 'cacao'),
            ('killimsa', 'carbón'),
            ('killka', 'letra'),
            ('killu', 'amarillo'),
            ('kimsa', 'tres'),
            ('kinti', 'colibrí'),
            ('kinuwa', 'quinoa'),
            ('kipchan', 'hígado'),
            ('kipi', 'maleta'),
            ('kiru', 'diente'),
            ('kisha', 'nido'),
            ('kita', 'arsico'),
            ('kiti', 'cantón'),
            ('kitilli', 'parroquia'),
            ('kiya', 'pus'),
            ('kuchu', 'rincón'),
            ('kuchuna', 'cortar'),
            ('kuchuyarina', 'acercarse'),
            ('kula', 'cacao'),
            ('kullan', 'taxo'),
            ('kullki', 'plata'),
            ('kullu', 'tronco'),
            ('kulta', 'pato'),
            ('kulun', 'trueno'),
            ('kumal', 'camote'),
            ('kumir', 'verde'),
            ('kunan', 'ahora'),
            ('kunana', 'aconsejar'),
            ('kunchu', 'residuo'),
            ('kunuk', 'caliente'),
            ('kuña', 'moco'),
            ('kupa', 'basura'),
            ('kuri', 'oro'),
            ('kurpa', 'terrón'),
            ('kuru', 'gusano'),
            ('kurunta', 'tusa'),
            ('kururu', 'ovillo'),
            ('kururuna', 'ovillar'),
            ('kusana', 'asar'),
            ('kushpi', 'peonza'),
            ('kuskunku', 'búho'),
            ('kutama', 'costal'),
            ('kutashka', 'harina'),
            ('kutana', 'moler'),
            ('kutichina', 'contestar'),
            ('kutu', 'bocio'),
            ('kutul', 'hoja'),
            ('kutuyana', 'encogerse'),
            ('kuna', 'dar'),
            ('kuy', 'cuy'),
            ('kuya', 'esposa'),
            ('kuyana', 'regalar'),
            # Sección L - Palabras que empiezan con 'l'
            ('lampa', 'pala'),
            ('lampana', 'remendar'),
            ('lanta', 'turbio'),
            ('lapuna', 'doblar'),
            ('larka', 'acequia'),
            ('latsik', 'gusano'),
            ('laychu', 'mestizo'),
            ('lumu', 'yuca'),
            ('lumucha', 'guanta'),
            ('lumarisu', 'moco'),

            # Sección LL - Palabras que empiezan con 'll'
            ('llachapana', 'remendar'),
            ('llachu', 'azadón'),
            ('llamkana', 'trabajar'),
            ('llampu', 'totalidad'),
            ('llantu', 'sombra'),
            ('llapina', 'aplastar'),
            ('llashak', 'pesado'),
            ('llashana', 'pesar'),
            ('llatan', 'desnudo'),
            ('llawana', 'lamer'),
            ('llakwarina', 'almorzar'),
            ('llurak', 'grillo'),
            ('llutkana', 'sacar'),
            ('llutuna', 'salir'),
            ('llutu', 'retoño'),
            ('llutsu', 'áspero'),
            ('lluykana', 'pelar'),
            ('lluylla', 'suave'),
            ('lliksina', 'ver'),
            ('lluksina', 'salir'),
            ('llaktaña', 'pintar'),
            ('llutuyana', 'gatear'),
            ('llamiki', 'camarón'),
            ('lliksiy', 'pestaña'),
            ('lliwa', 'gaviota'),
            ('lliklla', 'rebozo'),

            # Sección M - Palabras que empiezan con 'm'
            ('machakuy', 'olla'),
            ('manyayana', 'acercarse'),
            ('mañachina', 'prestar'),
            ('mapa', 'sucio'),
            ('marku', 'altamisa'),
            ('mapamari', 'sanguijuela'),
            ('masha', 'yerno'),
            ('mashna', '¿cuantos?'),
            ('mashu', 'murciélago'),
            ('mashi', 'compañero'),
            ('maykan', '¿cual?'),
            ('mati', 'mate'),
            ('mayllana', 'lavar'),
            ('mayma', 'inmenso'),
            ('mayta', '¿por donde?'),
            ('mayu', 'río'),
            ('michik', 'pastor'),
            ('mikuna', 'comida'),
            ('mikya', 'expresión'),
            ('millpuna', 'tragar'),
            ('milluku', 'melloco'),
            ('mimish', 'encías'),
            ('minka', 'trabajo'),
            ('mirka', 'peca'),
            ('misi', 'gato'),
            ('mita', 'época'),
            ('mitsa', 'verruga'),
            ('miyu', 'veneno'),
            ('miyuna', 'envenenar.'),
            ('munzira', 'constelación'),
            ('muray', 'hora'),
            ('muru', 'fruto'),
            ('muskuna', 'soñar'),
            ('muspana', 'tontea'),
            ('musyana', 'preeveer'),
            ('mutki', 'olfato'),
            ('mutkina', 'oler'),
            ('mutul', 'cartílago'),

            # Sección N - Palabras que empiezan con 'n'
            ('nanakllakana', 'abundar'),
            ('nanampi', 'bejuco'),
            ('nanay', 'dolor'),
            ('napaykuna', 'saludar'),
            ('nitkana', 'tropezar'),
            ('nina', 'decir'),
            ('nuspa', 'bromista'),
            ('nuyuna', 'inundarse'),

            # Sección Ñ - Palabras que empiezan con 'ñ'
            ('ñaka', 'antes'),
            ('ñakchana', 'peinar'),
            ('ñañu', 'delgado'),
            ('ñawsa', 'ciego'),
            ('ñuka', 'yo'),
            ('ñutku', 'cerebro'),

            # Sección P - Palabras que empiezan con 'p'
            ('pachak', 'cien, ciento'),
            ('pachakamak', 'dios.'),
            ('pakarinmikuna', 'desayunar.'),
            ('pakarina', 'amanecer.'),
            ('pakay', 'guaba.'),
            ('paktalla', 'mediano.'),
            ('paktamuna', 'llegar.'),
            ('paktana', 'alcanzar.'),
            ('pala', 'ancho.'),
            ('palata', 'caucho.'),
            ('palik', 'migaja.'),
            ('palikina', 'desmenuzar.'),
            ('pallta', 'aguacate.'),
            ('palu', 'lagartija.'),
            ('panchiy', 'febrero.'),
            ('panka', 'hoja.'),
            ('pañaña', 'piraña.'),
            ('paramuna', 'lloviznar.'),
            ('paruk', 'pulmón.'),
            ('paskana', 'despegar.'),
            ('paspa', 'paspa.'),
            ('patak', 'ancho.'),
            ('pati', 'bolso.'),
            ('patpa', 'pluma.'),
            ('patsak', 'bagazo.'),
            ('pawana', 'volar.'),
            ('pawkar', 'marzo.'),
            ('pi', '¿quien?'),
            ('pichka', 'cinco'),
            ('piki', 'pulga'),
            ('pillpintu', 'mariposa'),
            ('pimpirana', 'pestañar'),
            ('pinchi', 'canelo'),
            ('pinllu', 'lechero'),
            ('pintu', 'tela'),
            ('pircha', 'cardo'),
            ('pishiyana', 'escasear'),
            ('pishña', 'nutria'),
            ('pitalala', 'culebra'),
            ('piti', 'poco'),
            ('puchkana', 'hilar.'),
            ('puchukay', 'último.'),
            ('puchuna', 'sobrar.'),
            ('puka', 'rojo.'),
            ('pukla', 'lobanillo.'),
            ('pukllana', 'jugar.'),
            ('pukru', 'hondonada.'),
            ('pukshi', 'cal.'),
            ('pukuna', 'bodoquera.'),
            ('puluna', 'agujerear.'),
            ('puncha', 'día.'),
            ('punchana', 'guatusa.'),
            ('punsa', 'charco.'),
            ('punzuyana', 'erizarse'),
            ('puñuna', 'dormir'),
            ('pupu', 'ombligo'),
            ('puru', 'tutuma'),
            ('purutu', 'fréjol'),
            ('pusak', 'ocho'),
            ('pusun', 'panza'),
            ('putukulu', 'renacuajo'),
            ('puzun', 'panza'),

            # Sección R - Palabras que empiezan con 'r'
            ('raku', 'grueso'),
            ('rakuyana', 'engrosarse'),
            ('ransiw', 'extranjero'),
            ('rasuna', 'nevar'),
            ('rawa', 'surco'),
            ('rawchana', 'desramar'),
            ('rawrana', 'arder'),
            ('rikcharina', 'despertarse'),
            ('rikra', 'brazo'),
            ('riksina', 'conocer'),
            ('rimanakuna', 'dialogar'),
            ('rirpu', 'espejo'),
            ('rumikuta', 'cemento'),
            ('rumiyana', 'petrificarse'),
            ('rumpu', 'planeta'),
            ('runakay', 'humanidad'),
            ('runtu', 'granizo'),
            ('runtuna', 'granizar'),
            ('rupachina', 'incendiar'),
            ('rupay', 'calor'),

            # Sección S - Palabras que empiezan con 's'
            ('sachawakra', 'danta'),
            ('saksana', 'hartarse'),
            ('salamanka', 'brujo'),
            ('samana', 'descansar'),
            ('sampi', 'canilla'),
            ('sanku', 'turbio'),
            ('sañu', 'teja'),
            ('sapallu', 'sapallo'),
            ('sapan', 'cada'),
            ('sapiyana', 'enraizarse'),
            ('sara', 'maíz'),
            ('sasina', 'ayunar'),
            ('sayrina', 'fumar'),
            ('siku', 'guatusa'),
            ('sillkukis', 'semana'),
            ('simpa', 'trenza'),
            ('simpana', 'trenzar'),
            ('sipu', 'arruga'),
            ('sisa', 'flor'),
            ('suchu', 'tullido'),
            ('suchuna', 'arrastrarse'),
            ('suksu', 'mirlo'),
            ('sukta', 'seis'),
            ('sukus', 'carrizo'),
            ('sulluy', 'aborto'),
            ('supi', 'pedo'),
            ('supina', 'peer'),
            ('surkan', 'pulmón'),
            ('surkuna', 'sacar'),
            ('susu', 'polilla'),
            ('susuna', 'apolillarse'),
            ('suyu', 'región'),

            # Sección SH - Palabras que empiezan con 'sh'
            ('shamuna', 'venir'),
            ('shayak', 'vertical'),
            ('shikina', 'descamar'),
            ('shikra', 'bolso'),
            ('shikshi', 'sarna'),
            ('shiktikuy', 'ciempiés'),
            ('shillinkuk', 'travieso'),
            ('shillinkuna', 'fastidiar'),
            ('shimi-chinkachina', 'delirar'),
            ('shiminchina', 'hacer bordes'),
            ('shimiyuk', 'diccionario'),
            ('shina', 'como'),
            ('shinallatak', 'pero'),
            ('shinki', 'carbón'),
            ('shirinka', 'caucho'),
            ('shitana', 'brujear'),
            ('shiway', 'ciempiés'),
            ('shuk', 'uno'),
            ('shukkuna', 'unidades'),
            ('shukarina', 'atrancar'),
            ('shuklla', 'único'),
            ('shulluy', 'aborto'),
            ('shunku', 'corazón'),
            ('shunkuy', 'desayunar'),
            ('shuti', 'nombre'),
            ('shutu', 'gota'),
            ('shuturina', 'mojarse'),
            ('shuwa', 'ladrón'),
            ('shuwana', 'robar'),
            ('shuyana', 'esperar'),
            ('shuyuna', 'manchar'),

            # Sección T - Palabras que empiezan con 't'
            ('takla', 'flojo'),
            ('taklla', 'arado'),
            ('takllana', 'ajustar'),
            ('takllu', 'tartamudo'),
            ('taksu', 'taxo'),
            ('taktarina', 'endurarse'),
            ('takurina', 'insultar'),
            ('talpa', 'blusa'),
            ('tamya', 'lluvia'),
            ('tamyana', 'llover'),
            ('tani', 'agrio'),
            ('tanta', 'pan'),
            ('tarinakuna', 'encontrarse'),
            ('taripay', 'examen'),
            ('tarpuna', 'sembrar'),
            ('taruka', 'venado'),
            ('taski', 'cascada'),
            ('tatis', 'ciempiés'),
            ('tatki', 'paso'),
            ('tawna', 'bastón'),
            ('tawri', 'chocho'),
            ('tiklla', 'mancha'),
            ('tiksimuyuyachay', 'geografía'),
            ('tillimpu', 'luciérnaga'),
            ('tinkana', 'papirotear'),
            ('tinkuna', 'unir'),
            ('titi', 'plomo'),
            ('tiyarpa', 'tartamudo'),
            ('tuka', 'saliva'),
            ('tukru', 'cuágulo'),
            ('tuksina', 'jeringuilla'),
            ('tukuchishka', 'concluido'),
            ('tukyachina', 'reventar'),
            ('tula', 'estaca'),
            ('tularina', 'derrumbarse'),
            ('tullpa', 'fogón'),
            ('tullumpa', 'palanca'),
            ('tulun', 'trueno'),
            ('tumpina', 'apuntalar'),
            ('tunchi', 'alma'),
            ('tuñirina', 'derrumbarse'),
            ('tupana', 'encontrarse'),
            ('tupu', 'prendedor'),
            ('tupuna', 'medir'),
            ('tushuna', 'bailar'),
            ('tuta', 'noche'),
            ('tutayana', 'anochecerse'),
            ('tuyaka', 'remanso'),

                # Sección TS - Palabras que empiezan con 'ts'
            ('tsalanchuspi', 'zancudo'),
            ('tsimukina', 'pestañear'),
            ('tsitsikina', 'pellizcar'),
            ('tsutsuk', 'puñado'),

            # Sección U - Palabras que empiezan con 'u'
            ('uchilla', 'pequeño'),
            ('uchpa', 'ceniza'),
            ('uchu', 'ají'),
            ('uhu', 'tos'),
            ('uhuna', 'toser'),
            ('uka', 'oca'),
            ('ukku', 'cuerpo'),
            ('ukllana', 'abrazar'),
            ('ukucha', 'ratón'),
            ('ukun', 'cuerpo'),
            ('ullawanka', 'gallinazo'),
            ('ullu', 'pene'),
            ('uma', 'cabeza'),
            ('umu', 'sacerdote'),
            ('umutu', 'enano'),
            ('unkushka', 'enfermo'),
            ('unkuy', 'enfermedad'),
            ('unkuna', 'enfermarse'),
            ('upallana', 'callarse'),
            ('uputinti', 'alacrán'),
            ('uray', 'abajo'),
            ('uritu', 'lora'),
            ('urmana', 'caerse'),
            ('urpi', 'tórtola'),
            ('uru', 'araña'),
            ('usa', 'piojo'),
            ('usana', 'despiojar'),
            ('ushku', 'gallinazo'),
            ('ushushi', 'hija'),
            ('uspun', 'panza'),
            ('usuna', 'abundar'),
            ('utku', 'algodón'),
            ('uturunku', 'tigre'),

            # Sección W - Palabras que empiezan con 'w'
            ('wacharina', 'nacer'),
            ('wachi', 'lanza'),
            ('wachu', 'surco'),
            ('waka', 'desigual'),
            ('wakamayu', 'guacamayo'),
            ('wakar', 'garza'),
            ('wakarina', 'oxidarse'),
            ('wakana', 'llorar'),
            ('wakayana', 'desigualarse'),
            ('wakcha', 'pobre'),
            ('wakin', 'algún'),
            ('wakillina', 'dañar'),
            ('wallinku', 'conejo'),
            ('wallpa', 'gallina'),
            ('wallu', 'cántaro'),
            ('wampu', 'barco'),
            ('wanchaka', 'raposa'),
            ('wankana', 'jabalí'),
            ('wankar', 'tambor'),
            ('wantuk', 'floripondio'),
            ('wanu', 'abono'),
            ('wañushka', 'mortecina'),
            ('wañuy', 'muerte'),
            ('wara', 'pantalón'),
            ('waranka', 'mil'),
            ('warkuna', 'colgar'),
            ('warmi', 'mujer'),
            ('wawa', 'niño'),
            ('wata', 'año'),
            ('watawata', 'salamanquesa'),
            ('waturitu', 'pavo nocturno'),
            ('watuna', 'adivinar'),
            ('waylla', 'verde'),
            ('wayna', 'joven'),
            ('wayra', 'viento'),
            ('waytana', 'nadar'),
            ('wichayana', 'subir'),
            ('wichi', 'cazuela'),
            ('wichu', 'escorbuto'),
            ('wiki', 'lágrima'),
            ('wikiyana', 'lagrimear'),
            ('willak', 'informante'),
            ('winku', 'encorvado'),
            ('wiñachik', 'adoptivo'),
            ('wiñachishka', 'adoptado'),
            ('wiñay', 'siempre'),
            ('wiru', 'caña'),
            ('wishina', 'cuchara'),
            ('wiwa', 'animal'),

            # Sección Y - Palabras que empiezan con 'y'
            ('yachachik', 'profesor'),
            ('yachachikuy', 'educación'),
            ('yachanawasi', 'escuela'),
            ('yachana', 'saber'),
            ('yachik', 'sabor'),
            ('yallika', 'bejuco'),
            ('yana', 'negro'),
            ('yanta', 'leña'),
            ('yanuna', 'cocinar'),
            ('yapachina', 'ganar'),
            ('yapay', 'suma'),
            ('yapana', 'aumentar'),
            ('yapuna', 'arar'),
            ('yarkay', 'hambre'),
            ('yawar', 'sangre'),
            ('yaykuna', 'entrar'),
            ('yaksi', 'arena'),
            ('yupay', 'número'),
            ('yurak', 'blanco'),
            ('yutu', 'perdiz'),
            ('yuyana', 'pensar'),
            ('yuyayyuk', 'pensante'),

            # Sección Z - Palabras que empiezan con 'z'
            ('zipi', 'paspa'),
            ('zullu', 'cigarra'),

            # Sección ZH - Palabras que empiezan con 'zh'
            ('zhapra', 'hojarasca'),
            ('zhuta', 'pájaro'),
            
        ]
        
        contador = 0
        for termino_kichwa, descripcion_espanol in palabras_juegos_kichwa_espanol:
            if termino_kichwa and descripcion_espanol:  # Verificar que no estén vacías
                # Extraer una traducción simple de la descripción (primeras palabras)
                traduccion_simple = descripcion_espanol.split('.')[0].split(',')[0][:50]
                
                categoria_nombre = self.determinar_categoria_juego(termino_kichwa, traduccion_simple, descripcion_espanol)
                categoria = Categoria.objects.get(nombre=categoria_nombre)
                dificultad = self.determinar_dificultad_juego(termino_kichwa, traduccion_simple, descripcion_espanol)
                
                palabra, created = Palabra.objects.get_or_create(
                    palabra_kichwa=termino_kichwa.strip(),
                    traduccion_espanol=traduccion_simple.strip(),
                    defaults={
                        'categoria': categoria,
                        'definicion': descripcion_espanol.strip(),
                        'descripcion_juego_espanol': descripcion_espanol.strip(),
                        'pronunciacion': f'[{termino_kichwa.strip()}]',
                        'nivel_dificultad': 'basico',
                        'dificultad_juego': dificultad,
                        'apta_para_juegos': True,
                        'activa': True,
                        'frecuencia_uso': 1,
                    }
                )
                
                if not created:
                    # Si ya existe, actualizar para juegos
                    palabra.apta_para_juegos = True
                    palabra.descripcion_juego_espanol = descripcion_espanol.strip()
                    palabra.dificultad_juego = dificultad
                    palabra.frecuencia_uso += 1
                    palabra.save()
                
                contador += 1
                if contador % 50 == 0:
                    self.stdout.write(f'Procesadas {contador} palabras kichwa-español para juegos...')
        
        self.stdout.write(f'Cargadas {contador} palabras kichwa-español para juegos')

    @transaction.atomic
    def cargar_palabras_juegos_espanol_kichwa(self):
        """Carga las 1550 palabras español-kichwa para juegos"""
        self.stdout.write('Cargando palabras español-kichwa para juegos...')
        
        # ============================================
        # COPIA Y PEGA AQUÍ TUS 1550 PALABRAS ESPAÑOL-KICHWA PARA JUEGOS
        # Formato: ('término_español', 'descripción_en_kichwa'),
        # ============================================
        palabras_juegos_espanol_kichwa = [
            # Ejemplos (reemplaza con tus datos reales):
            # Sección A - Palabras que empiezan con 'a'
            ('abdomen', 'wiksa'),
            ('abismo', 'kaka'),
            ('abortar', 'shulluna'),
            ('abrazar', 'ukllana'),
            ('abrigado', 'kunuk'),
            ('abril', 'ayriwa'),
            ('acabarse', 'tukurina'),
            ('acarrear', 'astana'),
            ('aceite', 'wira'),
            ('acelerar', 'utkana'),
            ('achera', 'achira'),
            ('achogcha', 'achukcha'),
            ('achupalla', 'achupalla'),
            ('aconsejar', 'kunana'),
            ('acordarse', 'yuyarina'),
            ('acostarse', 'siririna'),
            ('acostumbrado', 'yacharishka'),
            ('acostumbrarse', 'yacharina'),
            ('acrecentar', 'mirachina'),
            ('actual', 'kunan'),
            ('aculturado', 'chasu'),
            ('acuñar', 'kanichina'),
            ('adelantarse', 'ñawparina'),
            ('además', 'ashtawan'),
            ('adherirse', 'llutarina'),
            ('adivinar', 'watuna'),
            ('adivino', 'watuk'),
            ('adobe', 'tika'),
            ('adónde?', '¿maymantak?'),
            ('adoptado', 'wiñachishka'),
            ('adoptivo', 'wiñachik'),
            ('adorar', 'muchana'),
            ('adulto', 'shunkuyuk'),
            ('adversidad', 'chiki'),
            ('advertir', 'willana'),
            ('aferrado', 'llumi'),
            ('aficionar', 'munana'),
            ('afiliarse', 'llutarina'),
            ('afligirse', 'llakirina'),
            ('agachar', 'kumuna'),
            ('agente', 'chapak'),
            ('agitarse', 'kuyuna'),
            ('agolpar', 'ñitina'),
            ('agónico', 'ayakara'),
            ('agosto', 'chakmay'),
            ('agradable', 'mishkichiypak'),
            ('agradecer', 'yupaychana'),
            ('agregar', 'yapana'),
            ('agua', 'yaku'),
            ('aguacate', 'pallta'),
            ('aguado', 'chuya'),
            ('aguardar', 'shuyana'),
            ('agujero', 'hutku'),
            ('agusanarse', 'kuruyana'),
            ('aguzado', 'ñawchi'),
            ('ahora', 'kunan'),
            ('ahorcar', 'sipina'),
            ('alargado', 'suniyashka'),
            ('alargar', 'suniyachina'),
            ('alargarse', 'suniyana'),
            ('alabarse', 'chakchuna'),
            ('alacrán', 'uputinti'),
            ('alforja', 'wayaka'),
            ('algún', 'wakin'),
            ('aliento', 'samay'),
            ('alimentar', 'karana'),
            ('alimentarse', 'mikuna'),
            ('almacén', 'katuwasi'),
            ('almohada', 'sawna'),
            ('altamisa', 'marku'),
            ('alterarse', 'piñarina'),
            ('alzarse', 'hatarina'),
            ('amamantar', 'chuchuchina'),
            ('amanecer', 'pakarina'),
            ('amontonar', 'tantachina'),
            ('amuleto', 'wakanki'),
            ('anaconda', 'yakumama'),
            ('anatomía', 'ukunyachay'),
            ('anciana', 'paya'),
            ('andar', 'purina'),
            ('angosto', 'kichki'),
            ('anonadarse', 'upayana'),
            ('anormal', 'paku'),
            ('antojar', 'munana'),
            ('anunciar', 'willana'),
            ('apaciguar', 'kasiyachina'),
            ('aparecerse', 'rikurina'),
            ('aparentar', 'tukuna'),
            ('aparte', 'chikan'),
            ('apegarse', 'llutarina'),
            ('apellido', 'ayllushuti'),
            ('aplanar', 'allana'),
            ('aprender', 'yachakuna'),
            ('aprendiz', 'yachakuk'),
            ('apresar', 'hapina'),
            ('apretar', 'ñitina'),
            ('aquel', 'chakay'),
            ('araña', 'uru'),
            ('arar', 'yapuna'),
            ('arder', 'rawrana'),
            ('arderse', 'ruparina'),
            ('aretes', 'rinriwarkuna'),
            ('arisco', 'kita'),
            ('armazón', 'panshi'),
            ('arrastrar', 'aysana'),
            ('arrastrarse', 'suchuna'),
            ('arrepentirse', 'nanarina'),
            ('arrugar', 'sipuna'),
            ('articulación', 'muku'),
            ('artículo', 'kamachiy'),
            ('arvejas', 'alwis'),
            ('asamblea', 'tantanakuy'),
            ('asar', 'kusana'),
            ('asco', 'atatay'),
            ('asemejarse', 'rikchana'),
            ('asentir', 'iñina'),
            ('asesinar', 'wañuchina'),
            ('asiento', 'tiyarina'),
            ('asir', 'hapina'),
            ('asolear', 'mashana'),
            ('asomarse', 'rikurina'),
            ('asquear', 'millana'),
            ('astrólogo', 'pacha-unanchaq'),
            ('asustar', 'manchachina'),
            ('asustarse', 'mancharina'),
            ('atajar', 'harkana'),
            ('atardecer', 'chishiyana'),
            ('atemorizar', 'manchachina'),
            ('atemorizarse', 'mancharina'),
            ('atender', 'uyana'),
            ('atleta', 'kallpak'),
            ('atmósfera', 'wapsi'),
            ('atormentarse', 'ñakarina'),
            ('atracar', 'ñitina'),
            ('atrasarse', 'kipayana'),
            ('aumento', 'miray'),
            ('aún', 'chayrak'),
            ('ausente', 'illak'),
            ('austral', 'hanansuyu'),
            ('auxiliar', 'yanapana'),
            ('auxilio', 'yanapay'),
            ('averiguar', 'tapuna'),
            ('avión', 'antanka'),
            ('avisar', 'willana'),
            ('aviso', 'willay'),
            ('ayer', 'kayna'),
            ('ayudar', 'yanapana'),
            ('ayunar', 'sasina'),
            ('azadón', 'llachu'),
            ('azúcar', 'akumishki'),
            ('azucena', 'amankay'),
            ('azuela', 'llakllana'),
            ('azul', 'ankas'),
            # Sección B - Palabras que empiezan con 'b'
            ('badea', 'hulun'),
            ('bailar', 'tushuna'),
            ('balancearse', 'walinyana'),
            ('balanza', 'aysana'),
            ('baldado', 'wistu'),
            ('banca', 'tiyarina'),
            ('bañarse', 'armarina'),
            ('barba', 'sunka'),
            ('barco', 'wampu'),
            ('barranco', 'wayku'),
            ('barredor', 'pichak'),
            ('barrendero', 'pichak'),
            ('barrer', 'pichana'),
            ('barrera', 'harka'),
            ('barriga', 'wiksa'),
            ('batir', 'kuyuchina'),
            ('beber', 'upyana'),
            ('bello', 'sumak'),
            ('besar', 'muchana'),
            ('bienestar', 'allikay'),
            ('bifurcación', 'pallka'),
            ('bigote', 'sunka'),
            ('bilingüe', 'ishkantinshimi'),
            ('blanco', 'yurak'),
            ('blusa', 'tallpa'),
            ('bocio', 'kutu'),
            ('bodoquera', 'pukuna'),
            ('borbotear', 'timpuna'),
            ('borde', 'manya'),
            ('bordes', 'shiminchina'),
            ('borrador', 'pichana'),
            ('borrar', 'pichana'),
            ('borrego', 'uwiha'),
            ('bosque', 'sacha'),
            ('breve', 'utka'),
            ('brindar', 'karana'),
            ('brindemos', 'ishkantishun'),
            ('buen', 'alli'),
            ('bulla', 'wanlla'),
            ('bulto', 'kipi'),
            # Sección C - Palabras que empiezan con 'c'
            ('cabaña', 'chuklla'),
            ('cabecera', 'sawna'),
            ('cabeza', 'uma'),
            ('cabuyo', 'chawar'),
            ('cada', 'sapan'),
            ('caerse', 'urmana'),
            ('caimito', 'hapiyu'),
            ('caldo', 'hilli'),
            ('calendario', 'pachakipu'),
            ('calentura', 'rupay'),
            ('calmar', 'kasiyachina'),
            ('camarón', 'lluchunka'),
            ('camilla', 'chakana'),
            ('camino', 'ñan'),
            ('camiseta', 'kushma'),
            ('candela', 'nina'),
            ('cangrejo', 'apankura'),
            ('cantante', 'takik'),
            ('cantar', 'takina'),
            ('cantón', 'kiti'),
            ('cárcel', 'wataywasi'),
            ('cardar', 'tisana'),
            ('cardo', 'pircha'),
            ('carear', 'chimpapurachina'),
            ('carnero', 'inku'),
            ('carnívoro', 'aychamikuk'),
            ('carpa', 'karpa'),
            ('carrizo', 'sukus'),
            ('cartílago', 'mutul'),
            ('casa', 'wasi'),
            ('casarse', 'sawarina'),
            ('casco', 'sillu'),
            ('casi', 'ñalla'),
            ('castellano', 'kastilla'),
            ('castillo', 'pukara'),
            ('casucha', 'chinkana'),
            ('catapulta', 'pallka'),
            ('catre', 'kawitu'),
            ('cauchoso', 'ankulla'),
            ('cazuela', 'wichi'),
            ('cebada', 'siwara'),
            ('cecina', 'charki'),
            ('cecinar', 'charkina'),
            ('cedazo', 'shushuna'),
            ('ceibo', 'putu'),
            ('cementerio', 'ayapampa'),
            ('cemento', 'rumikuta'),
            ('cenit', 'tiknu'),
            ('ceniza', 'uchpa'),
            ('cerbatana', 'pukuna'),
            ('cerca', 'kuchu'),
            ('cerco', 'kincha'),
            ('cerdo', 'kuchi'),
            ('cereal', 'murir'),
            ('cero', 'illak'),
            ('cerramiento', 'kincha'),
            ('cerrar', 'wichkana'),
            ('cerro', 'urku'),
            ('cesar', 'tukurina'),
            ('cesarse', 'samarina'),
            ('ciego', 'ñawsa'),
            ('cierto', 'chika'),
            ('cigarrillo', 'sayri'),
            ('cinco mil', 'pichka waranka'),
            ('cinco', 'pichka'),
            ('cincuenta', 'pichka chunka'),
            ('cintura', 'wikaw'),
            ('cinturón', 'chumpi'),
            ('círculo', 'muyu'),
            ('circunferencia', 'muyu'),
            ('ciruela', 'usun'),
            ('citar', 'kayana'),
            ('clase', 'sami'),
            ('clasificar', 'chikanyachina'),
            ('clavar', 'tuksina'),
            ('clavo', 'takarpu'),
            ('cobarde', 'sampa'),
            ('cobertor', 'katana'),
            ('cobijar', 'katana'),
            ('cobre', 'anta'),
            ('cocear', 'haytana'),
            ('cojear', 'hankana'),
            ('colación', 'kukayu'),
            ('colgado', 'warkushka'),
            ('colgar', 'warkuna'),
            ('colibrí', 'kinti'),
            ('colina', 'urku'),
            ('colocar', 'churana'),
            ('columna', 'tunu'),
            ('comadreja', 'chukuri'),
            ('comarca', 'llakta'),
            ('combinar', 'chakruna'),
            ('comenzar', 'kallarina'),
            ('comercializar', 'mintalana'),
            ('cometa', 'sasaka'),
            ('comezón', 'shikshi'),
            ('comienzo', 'kallari'),
            ('como', 'shina'),
            ('compatriota', 'llaktamashi'),
            ('complementado', 'paktachishka'),
            ('complementar', 'paktachina'),
            ('completar', 'paktachina'),
            ('comprar', 'rantina'),
            ('comprimir', 'ñitina'),
            ('comunicar', 'willana'),
            ('condimento', 'mishkichina'),
            ('conducir', 'pushana'),
            ('conejo', 'wallinku'),
            ('confundirse', 'pantana'),
            ('confusión', 'pantay'),
            ('congreso', 'tantanakuy'),
            ('conocer', 'riksina'),
            ('consejero', 'kunak'),
            ('cómo?', '¿haw?'),
            ('consuegra', 'hawya'),
            ('contaminación', 'miyuy'),
            ('contaminar', 'miyuna'),
            ('contento', 'kushilla'),
            ('conversación', 'rimanakuy'),
            ('conversar', 'rimana'),
            ('convidar', 'karana'),
            ('convocar', 'kayana'),
            ('cooperación', 'yanapay'),
            ('corcobado', 'kumu'),
            ('cordel', 'watu'),
            ('corona', 'llawtu'),
            ('coronilla', 'mukuku'),
            ('correa', 'chumpi'),
            ('correr', 'kallpana'),
            ('corteza', 'kara'),
            ('cosa', 'ima'),
            ('cosecha', 'pallay'),
            ('cosechador', 'pallak'),
            ('cosechar', 'pallana'),
            ('coser', 'sirana'),
            ('costal', 'kutama'),
            ('costra', 'karacha'),
            ('coya', 'kuya'),
            ('creencia', 'iñikuy'),
            ('creer', 'iñina'),
            ('creyente', 'iñikuk'),
            ('criado', 'china'),
            ('criado', 'yana'),
            ('criticar', 'washarimana'),
            ('crocante', 'kawlla'),
            ('crucificar', 'chakatana'),
            ('crudo', 'chawa'),
            ('cruz', 'chakata'),
            ('cuágulo', 'tukru'),
            ('¿cuál?', '¿maykan?'),
            ('¿cuándo?', '¿hayka?'),
            ('¿cuántos?', '¿mashna?'),
            ('cuarenta', 'chusku chunka'),
            ('cuatro mil', 'chusku waranka'),
            ('cucaracha', 'hallkan'),
            ('cuello', 'kunka'),
            ('cuerdo', 'llimpi'),
            ('cuero', 'kara'),
            ('culminación', 'tukuri'),
            ('culminar', 'tukuchina'),
            ('culo', 'siki'),
            ('culpa', 'hucha'),
            ('culpar', 'huchanchina'),
            ('cumbre', 'uma'),
            ('cuñada', 'kachun'),
            ('curiquingue', 'kurikinki'),
            ('curva', 'kinku'),
            ('curvar', 'kinkuna'),
            ('cuy', 'quwi'),
            # Sección CH - Palabras que empiezan con 'ch'
            ('chacra', 'chakra'),
            ('chamisa', 'chinta'),
            ('chamuscar', 'kaspana'),
            ('chancho', 'kuchi'),
            ('chibolo', 'zupu'),
            ('chichón', 'zupu'),
            ('chilca', 'chillka'),
            ('chillar', 'kaparina'),
            ('chímbalo', 'chimpalu'),
            ('chistoso', 'chawcha'),
            ('chivo', 'chita'),
            ('chocho', 'tawri'),
            ('chofer', 'purichik'),
            ('chorrear', 'shutuna'),
            ('chorrera', 'pakcha'),
            ('choza', 'chuklla'),
            ('chumado', 'shinka'),
            ('chumarse', 'shinkayana'),
            ('chonta', 'chunta'),
            ('chuquirahua', 'chukirawa'),
            # Sección D - Palabras que empiezan con 'd'
            ('danta', 'sachawakra'),
            ('danzante', 'tushuk'),
            ('danza', 'tushuy'),
            ('danzar', 'tushuna'),
            ('debajero', 'ukunchina'),
            ('década', 'chunkawata'),
            ('decaerse', 'urmarina'),
            ('decir', 'nina'),
            ('declamar', 'luwana'),
            ('declarado', 'willashka'),
            ('declarar', 'willana'),
            ('defecar', 'ismana'),
            ('deformarse', 'wistuna'),
            ('degollado', 'nakashka'),
            ('degollador', 'nakak'),
            ('degollar', 'nakana'),
            ('delante', 'ñawpak'),
            ('delantero', 'ñawpak'),
            ('delicado', 'chawcha'),
            ('delicioso', 'mishki'),
            ('demás', 'yalli'),
            ('demostrar', 'rikuchina'),
            ('demostrativo', 'rikuchik'),
            ('dentro', 'uku'),
            ('deposición', 'isma'),
            ('descamar', 'shikina'),
            ('descansar', 'samana'),
            ('descomponer', 'chakchuna'),
            ('descomponerse', 'putasyana'),
            ('descriarse', 'challana'),
            ('descuartizado', 'nakashka'),
            ('descuartizar', 'nakana'),
            ('desdeñar', 'hunkana'),
            ('desear', 'munana'),
            ('desgajar', 'llakllana'),
            ('desgastar', 'kaskana'),
            ('deshierbar', 'kiwana'),
            ('desigual', 'waka'),
            ('desigualar', 'wakayachina'),
            ('desigualarse', 'wakayana'),
            ('desleír', 'yakuyachina'),
            ('deslizarse', 'llushpina'),
            ('desmayarse', 'shinkana'),
            ('desnudarse', 'llatanana'),
            ('desobedecer', 'mana-uyana'),
            ('desobediente', 'mana-uyak'),
            ('desolado', 'chulunlla'),
            ('despejado', 'paklla'),
            ('despeñadero', 'kaka'),
            ('desperdiciar', 'usuchiy'),
            ('despertarse', 'rikcharina'),
            ('despiojar', 'usana'),
            ('despostillarse', 'tukyana'),
            ('despreciar', 'chiknina'),
            ('desvariar', 'tapyana'),
            ('desventura', 'llaki'),
            ('desvestirse', 'llatanarina'),
            ('desyerbar', 'hallmay'),
            ('detenerse', 'shayana'),
            ('deteriorar', 'wakllichina'),
            ('deuda', 'manu'),
            ('diadema', 'llawtu'),
            ('dialogar', 'rimanakuna'),
            ('diálogo', 'rimanakuy'),
            ('diccionario', 'shimiyuk'),
            ('diciembre', 'kapak'),
            ('dicho', 'nishka'),
            ('diente', 'kiru'),
            ('diez mil', 'hunu'),
            ('diez', 'chunka'),
            ('diferenciar', 'chikanyachina'),
            ('difunto', 'wañushka'),
            ('diluír', 'yakuyana'),
            ('diluirse', 'yakuyarina'),
            ('dinero', 'kullki'),
            ('dirección', 'kuska'),
            ('dirigente', 'pushak'),
            ('dirigir', 'pushana'),
            ('disculpar', 'kishpichina'),
            ('discursar', 'luwana'),
            ('disentería', 'yawarkicha'),
            ('disgustarse', 'piñarina'),
            ('dislocar', 'kiwina'),
            ('disparar', 'tukyachina'),
            ('dispensar', 'kishpichina'),
            ('distinto', 'chikan'),
            ('distribuir', 'rakina'),
            ('división', 'rakiy'),
            ('docente', 'yachachik'),
            ('doler', 'nanana'),
            ('dolerse', 'nanarina'),
            ('domingo', 'hawkay'),
            ('don', 'hachi'),
            ('¿dónde?', 'mayman?'),
            ('doña', 'mama'),
            ('dormido', 'puñushka'),
            ('dormiente', 'puñukuk'),
            ('dormir', 'puñuna'),
            ('dos mil', 'ishkay waranka'),
            ('dos', 'ishkay'),
            ('dudar', 'tunkina'),
            # Sección E - Palabras que empiezan con 'e'
            ('echarse', 'siririna'),
            ('educación', 'yachachikuy'),
            ('educador', 'yachachik'),
            ('ejemplar', 'shina'),
            ('ejemplo', 'shina'),
            ('él', 'pay'),
            ('elegante', 'taslla'),
            ('elegir', 'akllana'),
            ('elevado', 'hanak'),
            ('ella', 'pay'),
            ('ellas', 'paykuna'),
            ('embarrar', 'hawina'),
            ('embarrarse', 'turuyarina'),
            ('embellecer', 'sumakyana'),
            ('embobarse', 'upayarina'),
            ('embustero', 'challi'),
            ('embutir', 'ñitina'),
            ('empalagar', 'amina'),
            ('empalagoso', 'ñukñu'),
            ('empeorarse', 'anchayana'),
            ('empezado', 'kallarishka'),
            ('empezar', 'kallarina'),
            ('empollar', 'ukllay'),
            ('en dónde?', '¿maypitak?'),
            ('enero', 'kamay'),
            ('encanijarse', 'kintiyarina'),
            ('encapricharse', 'nanakyarina'),
            ('encargar', 'minkana'),
            ('encerrar', 'wichkay'),
            ('encharcarse', 'kuchayarina'),
            ('encías', 'mimish'),
            ('encima', 'hanak'),
            ('encolerizarse', 'piñarina'),
            ('encomendar', 'minkana'),
            ('enconarse', 'kiyayay'),
            ('encontrar', 'tarina'),
            ('encontrarse', 'tarinakurina'),
            ('encorralar', 'kinchana'),
            ('endurarse', 'taktariy'),
            ('enfermo', 'unkushka'),
            ('enfurecerse', 'millayarina'),
            ('engrosarse', 'rakuyana'),
            ('engullir', 'amullina'),
            ('enlagunarse', 'kuchayana'),
            ('enlodarse', 'turuyana'),
            ('enmudecerse', 'upayarina'),
            ('enraizarse', 'sapiyana'),
            ('enredar', 'pilluna'),
            ('enseñado', 'yacharishka'),
            ('enseñar', 'yachachina'),
            ('enseñarse', 'yacharina'),
            ('enserenado', 'ankulla'),
            ('ensuciar', 'hawina'),
            ('entablillar', 'chanchay'),
            ('enterrar', 'pampana'),
            ('entonar', 'takina'),
            ('entrada', 'punku'),
            ('entrar', 'yaykuna'),
            ('entrecruzar', 'chakatana'),
            ('entrelazar', 'chakatana'),
            ('entretejer', 'alapana'),
            ('entristecerse', 'llakirina'),
            ('enumerar', 'yupay'),
            ('enviar', 'kachana'),
            ('equivocación', 'pantay'),
            ('equivocado', 'pantashka'),
            ('equivocarse', 'pantarina'),
            ('erizarse', 'punzuyarina'),
            ('erosionarse', 'tularina'),
            ('errado', 'pantashka'),
            ('errar', 'pantana'),
            ('error', 'pantay'),
            ('eructar', 'aknina'),
            ('erupcionar', 'tukyana'),
            ('es verdad?', '¿manachu?'),
            ('esa', 'chay'),
            ('escabroso', 'sakra'),
            ('escalera', 'chakana'),
            ('escamar', 'tisana'),
            ('escarabajo', 'shuntu'),
            ('escarbar', 'aspina'),
            ('escarcha', 'shulla'),
            ('escasear', 'pishiyana'),
            ('escaso', 'pishi'),
            ('escoba', 'pichana'),
            ('escogedor', 'akllak'),
            ('escoger', 'akllana'),
            ('esconder', 'pakana'),
            ('esconderse', 'mitikurina'),
            ('escopeta', 'illapa'),
            ('escorbuto', 'wichu'),
            ('escribir', 'killkana'),
            ('escrito', 'killkashka'),
            ('escritor', 'killkaykamayuk'),
            ('escritorio', 'chakiqiru'),
            ('escuchar', 'uyana'),
            ('esculpir', 'llakllana'),
            ('escupir', 'aktuna'),
            ('escurrir', 'chawana'),
            ('ese', 'chay'),
            ('esfera', 'rumpu'),
            ('esferográfico', 'killkana'),
            ('eso', 'chay'),
            ('espalda', 'washa'),
            ('espantado', 'mancharishka'),
            ('espantar', 'manchachina'),
            ('espantarse', 'mancharina'),
            ('espanto', 'manchay'),
            ('español', 'wirakucha'),
            ('espejo', 'rirpu'),
            ('esperanza', 'shuyay'),
            ('esperar', 'shuyana'),
            ('espeso', 'sanku'),
            ('espíar', 'chapana'),
            ('espina', 'kasha'),
            ('espiral', 'churu'),
            ('espuma', 'pusku'),
            ('espumarse', 'puskuyarina'),
            ('esquina', 'kuchu'),
            ('esta', 'kay'),
            ('estaca', 'takarpu'),
            ('estacar', 'takarpuna'),
            ('estafa', 'ayki'),
            ('estado', 'aylluntintinkuy'),
            ('estafar', 'aykina'),
            ('estaño', 'titi'),
            ('estar', 'kana'),
            ('este', 'kay'),
            ('estércol', 'isma'),
            ('estilarse', 'hukurina'),
            ('estirar', 'chutana'),
            ('estirpe', 'panaka'),
            ('esto', 'kay'),
            ('estorbar', 'harkana'),
            ('estorbo', 'harka'),
            ('estornudar', 'atsikyana'),
            ('estrangular', 'sipina'),
            ('estrecho', 'kichki'),
            ('estrella', 'kuyllur'),
            ('estrenar', 'arina'),
            ('estudiado', 'yachakushka'),
            ('estudiante', 'yachakuk'),
            ('estudiar', 'yachakuna'),
            ('examen', 'taripay'),
            ('examinador', 'taripak'),
            ('examinar', 'taripay'),
            ('excavar', 'allana'),
            ('exceder', 'yallina'),
            ('excremento', 'isma'),
            ('excusar', 'kishpichina'),
            ('exigir', 'atina'),
            ('existir', 'tiyana'),
            ('expandirse', 'mirarina'),
            ('exprimir', 'kapina'),
            ('expulgar', 'usana'),
            ('extender', 'aysana'),
            ('extenso', 'suni'),
            ('exterior', 'hawa'),
            ('extremidad', 'puchukaynin'),
            # Sección F - Palabras que empiezan con 'f'
            ('falsear', 'llullana'),
            ('FALSO', 'llulla'),
            ('falta', 'hucha'),
            ('faltar', 'illana'),
            ('familia', 'ayllu'),
            ('fardo', 'kipi'),
            ('favorecer', 'yanapana'),
            ('faz', 'uya'),
            ('febrero', 'panchiy'),
            ('feliz', 'kushilla'),
            ('fermentarse', 'timpurina'),
            ('festividad', 'raymi'),
            ('fiambre', 'kukayu'),
            ('figura', 'rikchak'),
            ('fila', 'wachu'),
            ('filtrar', 'shutuna'),
            ('fin', 'tukuri'),
            ('fingir', 'tukuna'),
            ('firmar', 'aspina'),
            ('flecha', 'wachi'),
            ('flojo', 'takla'),
            ('floripondio', 'wantuk'),
            ('flotar', 'wampuna'),
            ('forcejear', 'chutanakuna'),
            ('fotografía', 'rikchak'),
            ('fracasar', 'kulluna'),
            ('fracaso', 'kulluy'),
            ('fracción', 'paki'),
            ('fractura', 'paki'),
            ('fracturar', 'pakina'),
            ('fragante', 'mishki'),
            ('frágil', 'kapya'),
            ('fréjol', 'purutu'),
            ('frente', 'tirku'),
            ('friolento', 'chirisiki'),
            ('fruncir', 'sipuna'),
            ('fuerte', 'sinchi'),
            ('fugarse', 'mitikuna'),
            ('fumar', 'sayrina'),
            ('fundamento', 'sapi'),
            # Sección G - Palabras que empiezan con 'g'
            ('galaxia', 'muyukchuru'),
            ('gallardo', 'taslla'),
            ('ganado vacuno', 'wakra'),
            ('ganar', 'mishana'),
            ('garganta', 'tunkuri'),
            ('gatear', 'llukana'),
            ('gato', 'misi'),
            ('gaviota', 'lluya'),
            ('gemido', 'shinshin'),
            ('genealogía', 'ayllu'),
            ('geografía', 'tiksimuyuyachay'),
            ('geógrafo', 'tiksimuyuyachak'),
            ('glúteos', 'siki'),
            ('gobernación', 'pushakuna'),
            ('goloso', 'hillu'),
            ('golpearse', 'takarina'),
            ('gordo', 'wira'),
            ('gotear', 'shutuna'),
            ('grada', 'pata'),
            ('granadilla', 'tintin'),
            ('grandeza', 'kapak'),
            ('granizar', 'runtuna'),
            ('granizo', 'runtu'),
            ('grasa', 'wira'),
            ('grasoso', 'wirasapa'),
            ('grieta', 'chikta'),
            ('gritar', 'kaparina'),
            ('grueso', 'raku'),
            ('guacamayo', 'wakamayu'),
            ('guanta', 'lumucha'),
            ('guardería', 'wawawasi'),
            ('guiar', 'pushana'),
            ('guineo', 'palanta'),
            ('guión', 'aspi'),
            ('guzhan', 'kullan'),
            # Sección H - Palabras que empiezan con 'h'
            ('haba', 'nuya'),
            ('haber', 'tiyana'),
            ('hábitat', 'pachamama'),
            ('hábito', 'yachariy'),
            ('habituado', 'yacharishka'),
            ('habituarse', 'yacharina'),
            ('habla', 'rimay'),
            ('hablante', 'rimak'),
            ('hacha', 'ayri'),
            ('halcón', 'waman'),
            ('hallar', 'tarina'),
            ('hartar', 'amina'),
            ('hartarse', 'saksana'),
            ('hasta dónde?', 'maykama?'),
            ('hastiar', 'amina'),
            ('he aquí', 'kayka'),
            ('heces', 'isma'),
            ('helada', 'kasa'),
            ('helar', 'kasana'),
            ('helecho', 'llashipa'),
            ('helicóptero', 'antachikaru'),
            ('herirse', 'chukrina'),
            ('hernia', 'pawacha'),
            ('hervir', 'timpuna'),
            ('hervívoro', 'kiwamikuk'),
            ('higuerón', 'ila'),
            ('hablar', 'rimana'),
            ('hijo', 'churi'),
            ('hija', 'ushushi'),
            ('hilado', 'puchkashka'),
            ('hilar', 'puchkana'),
            ('hilera', 'wachu'),
            ('hilo', 'puchka'),
            ('hincharse', 'punkirina'),
            ('honda', 'waraka'),
            ('hondonada', 'pukru'),
            ('honrar', 'yupaychana'),
            ('hora', 'muray'),
            ('horcón', 'mantakakakiru'),
            ('horizontal', 'sirik'),
            ('hortalizas', 'yuyu'),
            ('hospedar', 'minkachina'),
            ('hospedarse', 'minkarina'),
            ('hotel', 'tampu'),
            ('hoy', 'kunan'),
            ('hoya', 'pukru'),
            ('hoyo', 'hutku'),
            ('huanaco', 'wanaku'),
            ('hueco', 'hutku'),
            ('huero', 'huka'),
            ('huerta', 'muya'),
            ('huevo', 'lulun'),
            ('huir', 'mitikuna'),
            ('humanidad', 'runakay'),
            ('humareda', 'kushni'),
            ('humear', 'kushnichina'),
            ('húmedo', 'huku'),
            ('humita', 'huminta'),
            ('humo', 'kushni'),
            ('hundirse', 'washaykuna'),
            ('hombre', 'kari'),
            # Sección I - Palabras que empiezan con 'i'
            ('idea', 'yuyay'),
            ('idéntico', 'rikchak'),
            ('idioma', 'shimi'),
            ('igualmente', 'shinallatak'),
            ('iguana', 'hayampi'),
            ('imagen', 'rikchak'),
            ('imbécil', 'muspa'),
            ('impermeabilizar', 'wirana'),
            ('importante', 'hatun'),
            ('inadaptable', 'awka'),
            ('inca', 'inka'),
            ('incendiar', 'rupachina'),
            ('inclinar', 'kumuna'),
            ('indicación', 'rikuchiy'),
            ('indicar', 'rikuchina'),
            ('indómito', 'kita'),
            ('infectarse', 'kiyayana'),
            ('inferior', 'sullka'),
            ('inflamación', 'inta'),
            ('inflamarse', 'ruparina'),
            ('inflarse', 'punkina'),
            ('informar', 'willana'),
            ('infortunio', 'chiki'),
            ('ingenuo', 'muspa'),
            ('inhumar', 'pampana'),
            ('iniciar', 'kallarina'),
            ('inicio', 'kallari'),
            ('inmediatamente', 'ñapash'),
            ('inseminar', 'yayuna'),
            ('insistir', 'atina'),
            ('inteligencia', 'yuyay'),
            ('inteligente', 'yuyaysapa'),
            ('interacción', 'ruranakuy'),
            ('intercambiar', 'rantinakuna'),
            ('interior', 'uku'),
            ('interrogativo', 'tapuk'),
            ('interrogar', 'tapuna'),
            ('introducir', 'satina'),
            ('invitar', 'kayana'),
            ('invocar', 'mañana'),
            ('inyectar', 'tuksina'),
            # Sección J - Palabras que empiezan con 'j'
            ('jabalí', 'wankana'),
            ('jarra', 'shila'),
            ('jaspeado', 'puzu'),
            ('jengibre', 'akirinri'),
            ('jesús', 'apunchik'),
            ('jicama', 'hikama'),
            ('jora', 'hura'),
            ('jorobado', 'kumu'),
            ('jueves', 'patma'),
            ('juicio', 'yuyay'),
            ('juicioso', 'yuyaysapa'),
            ('julio', 'purun'),
            ('junio', 'inti'),
            ('júpiter', 'akapana'),
            ('juzgar', 'taripana'),
            # Sección L - Palabras que empiezan con 'l'
            ('laberinto', 'chinkana'),
            ('lactar', 'chuchuna'),
            ('ladrón', 'shuwa'),
            ('lagaña', 'chukni'),
            ('lágrima', 'wiki'),
            ('lagrimear', 'wikiyana'),
            ('lamentar', 'llakina'),
            ('lamentarse', 'ñakarina'),
            ('lamer', 'llawana'),
            ('lana', 'millma'),
            ('langosta', 'chillik'),
            ('lanza', 'wachi'),
            ('lápiz', 'killkana'),
            ('largo', 'suni'),
            ('lastimarse', 'chukrina'),
            ('lazo', 'tuklla'),
            ('leche', 'ñuñu'),
            ('lechero', 'pinllu'),
            ('leer', 'killkakatina'),
            ('legislador', 'kamachik'),
            ('legislar', 'kamachina'),
            ('lejos', 'karu'),
            ('lengua', 'kallu'),
            ('lengüeta', 'kallwa'),
            ('letra', 'killka'),
            ('levantamiento', 'hatariy'),
            ('levantarse', 'hatarina'),
            ('leyenda', 'ñawparimay'),
            ('liberar', 'kishpichina'),
            ('librar', 'kishpichina'),
            ('liendre', 'chiya'),
            ('lila', 'maywa'),
            ('limar', 'llampuna'),
            ('limitar', 'saywana'),
            ('limón', 'ishnul'),
            ('límite', 'saywa'),
            ('limpiar', 'pichana'),
            ('linaje', 'ayllu'),
            ('lindero', 'saywa'),
            ('líquido', 'yaku'),
            ('lirio', 'amankay'),
            ('lisiar', 'kiwina'),
            ('lisonjero', 'mishkishimi'),
            ('liviano', 'pankalla'),
            ('lobanillo', 'pukla'),
            ('lobo', 'atuk'),
            ('lóbulo', 'llutu'),
            ('loma', 'urku'),
            ('lomo', 'washa'),
            ('lucero', 'kuyllur'),
            ('lumbre', 'nina'),
            ('luminoso', 'hakan'),
            ('luna', 'killa'),
            ('lunar', 'ana'),
            ('lunes', 'sullka'),
            ('luz', 'achik'),

            # Sección LL - Palabras que empiezan con 'll'
            ('llanura', 'pampa'),
            ('llorar', 'wakana'),
            ('lloviznar', 'paramuna'),
            # Sección M - Palabras que empiezan con 'm'
            ('máchica', 'machka'),
            ('madre', 'mama'),
            ('madrecita', 'mamaku'),
            ('madrugada', 'tutamanta'),
            ('madurar', 'pukuna'),
            ('madurarse', 'kawllarina'),
            ('maestro', 'yachachik'),
            ('maguey', 'chawar'),
            ('magullar', 'llakana'),
            ('magullarse', 'rawmana'),
            ('malestar', 'champayana'),
            ('maleta', 'kipi'),
            ('maleza', 'sacha'),
            ('malhumorarse', 'millayana'),
            ('malograrse', 'hukana'),
            ('mamá', 'mama'),
            ('mamar', 'chuchuna'),
            ('mamífero', 'chuchuk'),
            ('manantial', 'pukyu'),
            ('mancera', 'charina'),
            ('mandar', 'kachana'),
            ('maniatar', 'watana'),
            ('manillas', 'makiwatana'),
            ('manteca', 'wira'),
            ('maqueño', 'yurimawas'),
            ('mar', 'mamakucha'),
            ('marchar', 'tatkina'),
            ('marearse', 'shinkana'),
            ('marido', 'kusa'),
            ('marrano', 'kuchi'),
            ('martes', 'kulla'),
            ('marzo', 'pawkar'),
            ('más', 'ashtawan'),
            ('mashua', 'mashuwa'),
            ('mata', 'yura'),
            ('matar', 'wañuchina'),
            ('matrimoniarse', 'sawarina'),
            ('mayo', 'aymuray'),
            ('mazamorra', 'api'),
            ('mazo', 'makana'),
            ('mazorca', 'kaspa'),
            ('medida', 'tupu'),
            ('medio', 'chawpi'),
            ('mediocre', 'sacha'),
            ('medir', 'tupuna'),
            ('melga', 'milka'),
            ('melloco', 'milluku'),
            ('memoria', 'yuyay'),
            ('mencionado', 'nishka'),
            ('mencionar', 'nina'),
            ('menor', 'sullka'),
            ('mensaje', 'willay'),
            ('mensajero', 'chaski'),
            ('mentir', 'llullana'),
            ('mentira', 'llulla'),
            ('mentiroso', 'llulla'),
            ('mercurio', 'rimsi'),
            ('merendar', 'chishinmikuna'),
            ('merienda', 'chishinmikuy'),
            ('mermar', 'anchuchina'),
            ('mes', 'killa'),
            ('metal', 'anta'),
            ('meter', 'satina'),
            ('metro', 'tatki'),
            ('mierda', 'isma'),
            ('migaja', 'palik'),
            ('mil', 'waranka'),
            ('milenio', 'warankawata'),
            ('mimar', 'kuyana'),
            ('mimbre', 'tiyamshi'),
            ('minuto', 'hayri'),
            ('mirarnos', 'rikunakushun'),
            ('mirlo', 'suksu'),
            ('mismo', 'kikin'),
            ('mitad', 'chawpi'),
            ('mocho', 'putu'),
            ('mocosos', 'isi'),
            ('modificar', 'allichiy'),
            ('moho', 'allu'),
            ('mojado', 'huku'),
            ('moler', 'kutana'),
            ('molido', 'kuta'),
            ('molle', 'mulli'),
            ('mollera', 'ñupu'),
            ('montaña', 'urku'),
            ('montar', 'sikana'),
            ('monte', 'urku'),
            ('morada', 'tiyana'),
            ('morado', 'maywa'),
            ('morder', 'kanina'),
            ('morir', 'wañuna'),
            ('morirse', 'wañurina'),
            ('morocho', 'muruchu'),
            ('mortecina', 'ismushka'),
            ('mosca', 'chuspi'),
            ('mosquearse', 'intuna'),
            ('mostrar', 'rikuchina'),
            ('mote', 'muti'),
            ('moverse', 'kuyuna'),
            ('movilizar', 'kuyuchina'),
            ('mozuela', 'pasña'),
            ('muchacha', 'kuytsa'),
            ('muchacho', 'wamra'),
            ('mucho', 'achka'),
            ('mudo', 'upa'),
            ('muela', 'mamakiru'),
            ('muerte', 'wañuy'),
            ('muerto', 'wañushka'),
            ('mujer', 'warmi'),
            ('mujercita', 'mamaku'),
            ('muletilla', 'imashnaray'),
            ('multiplicar', 'mirachina'),
            ('multiplicarse', 'mirana'),
            ('mundo', 'pacha'),
            ('muñeca', 'llullawawa'),
            ('murciélago', 'mashu'),
            ('muro', 'pirka'),
            ('mutilar', 'kulluna'),
            ('muy', 'may'),
            # Sección N - Palabras que empiezan con 'n'
            ('nacer', 'wacharina'),
            ('nacido', 'wacharishka'),
            ('nación', 'llakta'),
            ('nacionalidad', 'suyukawsay'),
            ('nadar', 'waytana'),
            ('nadie', 'manapi'),
            ('nalga', 'siki'),
            ('nalgadas', 'kullpina'),
            ('naranja', 'laranka'),
            ('nariz', 'sinka'),
            ('narrar', 'hawarikuy'),
            ('naturaleza', 'pacha'),
            ('nausear', 'kuynana'),
            ('navegante', 'wampuk'),
            ('navegar', 'wampuna'),
            ('neblina', 'puyu'),
            ('necio', 'atupa'),
            ('negro', 'yana'),
            ('neptuno', 'turumanya'),
            ('nevado', 'rasushka'),
            ('nevar', 'rasuna'),
            ('nido', 'kisha'),
            ('niebla', 'puyu'),
            ('nieve', 'rasu'),
            ('nigua', 'iñu'),
            ('niña', 'pichiw'),
            ('niño', 'wawa'),
            ('nivelar', 'allana'),
            ('no', 'ama'),
            ('noble', 'kapak'),
            ('noche', 'tuta'),
            ('nogal', 'tukti'),
            ('nombre', 'shuti'),
            ('nosotros', 'ñukanchik'),
            ('novecientos', 'iskun pachak'),
            ('noventa', 'iskun chunka'),
            ('noviembre', 'ayar'),
            ('nube', 'puyu'),
            ('nublarse', 'puyuna'),
            ('nuca', 'washa'),
            ('núcleo', 'shunku'),
            ('numerar', 'yupana'),
            ('número', 'yupay'),
            ('nueve', 'mushuk'),
            ('nada', 'mana'),
            # Sección O - Palabras que empiezan con 'o'
            ('obstaculizar', 'harkana'),
            ('obstáculo', 'harka'),
            ('oca', 'uka'),
            ('ocho', 'pusak'),
            ('ocioso', 'killa'),
            ('octubre', 'yaku'),
            ('odiar', 'chiknina'),
            ('ofrecer', 'kuna'),
            ('oir', 'uyana'),
            ('olfato', 'mutki'),
            ('olla', 'manka'),
            ('oloroso', 'ashnak'),
            ('olvidado', 'kunkashka'),
            ('olvidar', 'kunkana'),
            ('olvido', 'kunkay'),
            ('ombligo', 'pupu'),
            ('omnívoro', 'tukuymikuk'),
            ('omóplato', 'karmin'),
            ('oprimir', 'ñitina'),
            ('orientación', 'rikuchiy'),
            ('origen', 'sapi'),
            ('orilla', 'manya'),
            ('ortiga', 'chini'),
            ('ortigar', 'chinina'),
            ('orzuelo', 'itsipu'),
            ('oscilar', 'walinyana'),
            ('oso', 'ukumari'),
            ('otra vez', 'kutin'),
            ('oveja', 'llama'),
            ('ovillar', 'kururuna'),
            ('ovillo', 'kururu'),
            ('oxidarse', 'wakarina'),
            ('oyente', 'uyak'),
            # Sección P - Palabras que empiezan con 'p'
            ('padre', 'yaya'),
            ('paludismo', 'chukchu-unkuy'),
            ('pan', 'tanta'),
            ('pantorilla', 'chakichichu'),
            ('panza', 'pusun'),
            ('papá', 'yaya'),
            ('papirotear', 'tinkana'),
            ('parar', 'shayarina'),
            ('parecerse', 'rikchana'),
            ('pariente', 'ayllu'),
            ('parir', 'wachana'),
            ('parroquia', 'kitilli'),
            ('parte', 'rakiy'),
            ('pasar', 'yallina'),
            ('pasear', 'puriykachana'),
            ('pastar', 'michina'),
            ('pastorear', 'michina'),
            ('patalear', 'kushparina'),
            ('patata', 'papa'),
            ('patear', 'haytana'),
            ('patio', 'kancha'),
            ('patrono', 'llamkayyuk'),
            ('pausa', 'samay'),
            ('peca', 'mirka'),
            ('pecado', 'hucha'),
            ('pecador', 'huchallik'),
            ('pecar', 'huchallina'),
            ('pecho', 'kasku'),
            ('pedo', 'supi'),
            ('peer', 'supina'),
            ('peinar', 'ñakchana'),
            ('peine', 'ñakcha'),
            ('peinilla', 'ñakcha'),
            ('pellejo', 'kara'),
            ('pelo', 'akcha'),
            ('pelota', 'rumpa'),
            ('pelusa', 'akwas'),
            ('penco', 'chawar'),
            ('pene', 'ullu'),
            ('pensamiento', 'yuyay'),
            ('pensar', 'yuyana'),
            ('peña', 'kaka'),
            ('perdón?', '¿haw?'),
            ('perdonar', 'kishpichina'),
            ('período', 'mita'),
            ('permitir', 'kacharina'),
            ('perseguir', 'katiykachana'),
            ('pescado', 'challwa'),
            ('petrificarse', 'rumiyana'),
            ('pezuña', 'sillu'),
            ('picante', 'hayak'),
            ('pícaro', 'challi'),
            ('pie', 'chaki'),
            ('piel', 'kara'),
            ('pinchar', 'tuksina'),
            ('pintón', 'ankas'),
            ('piña', 'chiwilla'),
            ('piola', 'kawchu'),
            ('piraña', 'paña'),
            ('piso', 'pata'),
            ('pizarrón', 'killkanapirka'),
            ('placenta', 'wawamama'),
            ('planeta', 'rumpu'),
            ('planicie', 'pampa'),
            ('plata, mineral', 'kullki'),
            ('plátano', 'palanta'),
            ('plegar', 'patarina'),
            ('plomo', 'titi'),
            ('pluma', 'patpa'),
            ('poblar', 'llaktana'),
            ('podrirse', 'ismuna'),
            ('poeta', 'arawikuk'),
            ('policía', 'chapak'),
            ('polilla', 'susu'),
            ('polinizar', 'yayuna'),
            ('polvo', 'allpa'),
            ('ponderarse', 'chakchuna'),
            ('pondo', 'puntu'),
            ('poner', 'churana'),
            ('por dónde?', '¿maytatak?'),
            ('por qué?', '¿imamantatak?'),
            ('por ello', 'chayrayku'),
            ('porfiar', 'atina'),
            ('posada', 'tampu'),
            ('potrero', 'muya'),
            ('pozo', 'pukyu'),
            ('precepto', 'kamachikuska'),
            ('precio', 'chanin'),
            ('precioso', 'sumak'),
            ('predecesor', 'ñawpak'),
            ('preguntar', 'tapuna'),
            ('prendedor', 'tupu'),
            ('preñada', 'chichu'),
            ('preñarse', 'chichuyana'),
            ('preparar', 'allichina'),
            ('presentador', 'riksichik'),
            ('presentar', 'riksichina'),
            ('presentarse', 'rikurina'),
            ('presente', 'kunan'),
            ('presidente', 'pushak'),
            ('prestar', 'mañachina'),
            ('prevalecer', 'atina'),
            ('prever', 'musyana'),
            ('princesa', 'ñusta'),
            ('príncipe', 'awki'),
            ('principiar', 'kallarina'),
            ('prisión', 'wataywasi'),
            ('propagación', 'miray'),
            ('propio', 'kikin'),
            ('provincia', 'marka'),
            ('pueblo', 'llakta'),
            ('puente', 'chaka'),
            ('puerco', 'kuchi'),
            ('puerta', 'punku'),
            ('puesto', 'kuska'),
            ('pujar', 'hipana'),
            ('pulga', 'piki'),
            ('pulir', 'llampuna'),
            ('pulsera', 'makiwatana'),
            ('pulverizar', 'ñutuna'),
            ('punta', 'ñawchi'),
            ('punto', 'iñu'),
            ('pupitre', 'pataku'),
            ('pus', 'kiya'),
            # Sección Q - Palabras que empiezan con 'q'
            ('qué dijo?', '¿haw?'),
            ('qué cosa?', 'ima'),
            ('quebrar', 'pakina'),
            ('quemar', 'rupachina'),
            ('quemarse', 'ruparina'),
            ('quichua', 'kichwa'),
            ('quién?', '¿pi?'),
            ('quieto', 'kasilla'),
            ('quinoa', 'kinuwa'),
            ('quipocamayoc', 'kipukamayuk'),
            ('quishuar', 'kishwar'),
            ('quitarse', 'anchurina'),

            # Sección R - Palabras que empiezan con 'r'
            ('rabo', 'chupa'),
            ('raíz', 'sapi'),
            ('rallar', 'shikina'),
            ('rama', 'mallki'),
            ('rapidísimo', 'ninantak'),
            ('rascar', 'aspina'),
            ('raspar', 'aspina'),
            ('ratón', 'ukucha'),
            ('raya', 'aspi'),
            ('rebasar', 'hichana'),
            ('recelo', 'pinkay'),
            ('rechoncho', 'kurpa'),
            ('recolectar', 'tantachina'),
            ('recordar', 'yuyarina'),
            ('recio', 'sinchi'),
            ('recuerdo', 'yuyariy'),
            ('refajo', 'ukunchina'),
            ('refinar', 'ñutuna'),
            ('reforzar', 'kimina'),
            ('regañar', 'piñachina'),
            ('reglamento', 'kamachiy'),
            ('reir', 'asina'),
            ('relampaguear', 'llipyana'),
            ('reloj', 'pacha'),
            ('rematar', 'alapana'),
            ('remedio', 'hampi'),
            ('remellar', 'llakana'),
            ('remellarse', 'rawmana'),
            ('remiendo', 'llachapa'),
            ('remojarse', 'nuyuna'),
            ('remorderse', 'nanarina'),
            ('repartir', 'rakina'),
            ('reprender', 'piñachina'),
            ('repugnar', 'millana'),
            ('resbalar', 'lluchkana'),
            ('resbalarse', 'llushpina'),
            ('resbaloso', 'lluchka'),
            ('reserva de alimentos', 'wanlla'),
            ('respetar', 'muchana'),
            ('respiración', 'samakuy'),
            ('resta', 'anchuchiy'),
            ('restar', 'anchuchina'),
            ('resto', 'puchu'),
            ('retirarse', 'anchurina'),
            ('retoñar', 'wiñana'),
            ('retoño', 'llulluk'),
            ('retrasarse', 'kipayana'),
            ('retrato', 'rikchak'),
            ('reunión', 'tantanakuy'),
            ('reunir', 'tantachina'),
            ('reventar', 'tukyana'),
            ('rezar', 'mañana'),
            ('rincón', 'kuchu'),
            ('riñón', 'rurun'),
            ('robar', 'shuwana'),
            ('robusto', 'sinchi'),
            ('rocío', 'shulla'),
            ('rodar', 'sinkuna'),
            ('rodilla', 'kunkuri'),
            ('roer', 'kaskana'),
            ('rogar', 'mañana'),
            ('rojo', 'puka'),
            ('roncar', 'harnina'),
            ('rosca', 'churu'),
            ('rostro', 'uya'),
            ('rótula', 'piruru'),
            ('rotura', 'paki'),
            ('rozar', 'waktana'),
            ('rozarse', 'takarina'),
            ('rubor', 'pinkay'),
            ('ruborizarse', 'pinkarina'),
            ('rústico', 'purun'),
            # Sección S - Palabras que empiezan con 's'
            ('sabiduría', 'yachay'),
            ('sabor', 'yachik'),
            ('sacapuntas', 'ñawchichina'),
            ('sacerdote', 'umu'),
            ('saeta', 'wachi'),
            ('safar', 'kacharina'),
            ('saíno', 'lumukuchi'),
            ('sal', 'kachi'),
            ('sala', 'pitita'),
            ('salamanchesca', 'watawata'),
            ('saliva', 'tuka'),
            ('salivar', 'tukana'),
            ('saltar', 'kushpana'),
            ('salud', 'allikay'),
            ('saludar', 'napaykuna'),
            ('salvar', 'kishpichina'),
            ('salvarse', 'kishpirina'),
            ('sandalia', 'ushuta'),
            ('sango', 'sanku'),
            ('sangorache', 'ataku'),
            ('sangre', 'yawar'),
            ('sanguijuela', 'mapamari'),
            ('sapallo', 'sapallu'),
            ('saquillo', 'tulu'),
            ('saturno', 'chimpu'),
            ('sauce', 'wayaw'),
            ('savia', 'llawsa'),
            ('seducir', 'kuyachina'),
            ('seis', 'sukta'),
            ('seleccionar', 'akllana'),
            ('selva', 'sacha'),
            ('semana', 'sillkukis'),
            ('sembrado', 'tarpushka'),
            ('sembrador', 'tarpuk'),
            ('sembrar', 'tarpuna'),
            ('semejante', 'shina'),
            ('semejanza', 'rikchak'),
            ('sendero', 'ñan'),
            ('seno', 'chuchu'),
            ('señora', 'mama'),
            ('septentrión', 'uraysuyu'),
            ('ser', 'kana'),
            ('sereno', 'kasilla'),
            ('seso', 'ñutku'),
            ('seta', 'kallampa'),
            ('si', 'ari'),
            ('siembra', 'tarpuy'),
            ('sien', 'wañuna'),
            ('siete', 'kanchis'),
            ('sigse', 'siksik'),
            ('silbar', 'hukipuna'),
            ('silla', 'tiyarina'),
            ('similar', 'shina'),
            ('sinuosidad', 'kinku'),
            ('soasar', 'ayampakuna'),
            ('sobar', 'kakuna'),
            ('sobrar', 'puchuna'),
            ('sobrepasar', 'yallina'),
            ('sobrio', 'mayllik'),
            ('sociable', 'maylla'),
            ('socorrer', 'yanapana'),
            ('solear', 'intina'),
            ('solearse', 'mashana'),
            ('solicitado', 'mañashka'),
            ('solicitar', 'mañana'),
            ('solitario', 'chiwillu'),
            ('solo', 'sapalla'),
            ('soltar', 'kacharina'),
            ('sombra', 'llantu'),
            ('sombrero', 'muchiku'),
            ('sombrilla', 'achiwa'),
            ('soñador', 'muskuk'),
            ('soñar', 'muskuna'),
            ('sopa', 'api'),
            ('sortija', 'shiwi'),
            ('sosegar', 'kasiyachina'),
            ('soto', 'sutu'),
            ('suceder', 'tukuna'),
            ('sudar', 'humpina'),
            ('sudor', 'humpi'),
            ('suelo', 'pampa'),
            ('sufrimiento', 'llaki'),
            ('sufrir', 'llakina'),
            ('suma', 'yapay'),
            ('sumar', 'yapana'),
            ('sumergirse', 'washaykuna'),
            ('superficial', 'hawalla'),
            ('supervisar', 'tukuyrikuna'),
            ('supervisor', 'tukuyrikuk'),
            ('suplicar', 'mañana'),
            ('suro', 'suru'),
            ('sustantivo', 'shuti'),
            # Sección T - Palabras que empiezan con 't'
            ('tabaco', 'sayri'),
            ('taita', 'yaya'),
            ('talega', 'wayaka'),
            ('talón', 'tayku'),
            ('tambalear', 'sinkuna'),
            ('tamo', 'tamu'),
            ('tapa', 'killpana'),
            ('tapar', 'killpana'),
            ('tarde', 'chishi'),
            ('tarea', 'ruray'),
            ('tartamudear', 'aklluna'),
            ('teatro', 'hawtaypata'),
            ('techar', 'katana'),
            ('teja', 'sañu'),
            ('tejer', 'awana'),
            ('tela', 'pintu'),
            ('telar', 'awanakaspi'),
            ('temático', 'paku'),
            ('temblar', 'chukchuna'),
            ('temer', 'manchana'),
            ('tender', 'mantana'),
            ('terminar', 'tukuchina'),
            ('testículo', 'lulun'),
            ('testimoniar', 'iñina'),
            ('teta', 'chuchu'),
            ('tiempo', 'pacha'),
            ('tienda', 'katuwasi'),
            ('tierno', 'llullu'),
            ('tiesto', 'kallana'),
            ('tigre', 'uturunku'),
            ('tinaja', 'mawma'),
            ('tintura', 'tullpu'),
            ('tío', 'hachi'),
            ('tipina', 'tipina'),
            ('tirar', 'shitana'),
            ('tiritar', 'chukchuna'),
            ('tiznarse', 'kushniyana'),
            ('tizón', 'inta'),
            ('tocte', 'tukti'),
            ('todavía no', 'manarak'),
            ('tontear', 'muspana'),
            ('tos', 'uhu'),
            ('toser', 'uhuna'),
            ('tostado', 'kamcha'),
            ('tostar', 'kamchana'),
            ('trabajador', 'llamkak'),
            ('traducir', 'tikrachina'),
            ('tragar', 'millpuna'),
            ('tranquilizar', 'kasiyachina'),
            ('tranquilo', 'kasilla'),
            ('transformación', 'pachakuti'),
            ('transformarse', 'tukuna'),
            ('transpirar', 'humpina'),
            ('trasladar', 'ashtana'),
            ('trasnocharse', 'pakarina'),
            ('trasquilar', 'rutuna'),
            ('trenza', 'chimpa'),
            ('trenzar', 'chimpana'),
            ('tres', 'kimsa'),
            ('trigo', 'triku'),
            ('triturar', 'chamkana'),
            ('troje', 'taki'),
            ('trompa', 'sinka'),
            ('trompetero', 'yakami'),
            ('tropezar', 'ñitkana'),
            ('tropezarse', 'ñitkarina'),
            ('trotar', 'kallpana'),
            ('trueno', 'kulun'),
            ('tú', 'kan'),
            ('tubo', 'tutu'),
            ('tullido', 'suchu'),
            ('tumor', 'chupu'),
            ('tumulto', 'wayka'),
            ('túnica', 'kushma'),
            ('tupido', 'kichki'),
            ('turbio', 'lanta'),
            ('tutuma', 'puru'),
            # Sección U - Palabras que empiezan con 'u'
            ('ubicar', 'churana'),
            ('ubre', 'chuchu'),
            ('universidad', 'hamutaywasi'),
            ('uno', 'shuk'),
            ('uña', 'sillu'),
            ('útero', 'wawatiyana'),

            # Sección V - Palabras que empiezan con 'v'
            ('vago', 'killa'),
            ('valeroso', 'sinchi'),
            ('valle', 'pampa'),
            ('vapor', 'wapsi'),
            ('variedad', 'sami'),
            ('varón', 'kari'),
            ('vegetal', 'yura'),
            ('veinte', 'ishkay chunka'),
            ('vejiga', 'ishpapuru'),
            ('velludo', 'millmasapa'),
            ('vencer', 'atina'),
            ('vendaje', 'yapa'),
            ('vender', 'katuna'),
            ('venerar', 'muchana'),
            ('venir', 'shamuna'),
            ('ventana', 'tuku'),
            ('ventura', 'kushi'),
            ('verdad', 'chika'),
            ('vergüenza', 'pinkay'),
            ('verter', 'tallina'),
            ('vertiente', 'pukyu'),
            ('vía', 'ñan'),
            ('vicuña', 'wikuña'),
            ('vida', 'kawsay'),
            ('vidrio', 'kispi'),
            ('vientre', 'wiksa'),
            ('viernes', 'haycha'),
            ('viga', 'kiru'),
            ('viniente', 'shamuk'),
            ('violar', 'wakllichina'),
            ('virar', 'tikrana'),
            ('viruela', 'muru-unkuy'),
            ('viruta', 'punzu'),
            ('viscoso', 'llawsa'),
            ('vista', 'ñawi'),
            ('viuda', 'wakcha'),
            ('viviente', 'kawsak'),
            ('vivir', 'kawsana'),
            ('vulva', 'raka'),

            # Sección Y - Palabras que empiezan con 'y'
            ('ya', 'ña'),
            ('yerno', 'masha'),
            ('yeso', 'isku'),
            ('yo', 'ñuka'),
            ('yuca', 'lumu'),

            # Sección Z - Palabras que empiezan con 'z'
            ('zapato', 'ushuta'),
            ('zarcillos', 'rinriwarkuna'),
            ('zorrillo', 'añas'),
            
        ]
        
        contador = 0
        for termino_espanol, descripcion_kichwa in palabras_juegos_espanol_kichwa:
            if termino_espanol and descripcion_kichwa:  # Verificar que no estén vacías
                # Extraer una traducción simple de la descripción (primera palabra en kichwa)
                traduccion_kichwa = descripcion_kichwa.split(',')[0].split(' ')[0]
                
                categoria_nombre = self.determinar_categoria_juego(traduccion_kichwa, termino_espanol, descripcion_kichwa)
                categoria = Categoria.objects.get(nombre=categoria_nombre)
                dificultad = self.determinar_dificultad_juego(traduccion_kichwa, termino_espanol, descripcion_kichwa)
                
                # Verificar si ya existe esta combinación
                palabra_existente = Palabra.objects.filter(
                    palabra_kichwa=traduccion_kichwa.strip(),
                    traduccion_espanol=termino_espanol.strip()
                ).first()
                
                if palabra_existente:
                    # Actualizar palabra existente para juegos
                    palabra_existente.apta_para_juegos = True
                    palabra_existente.descripcion_juego_kichwa = descripcion_kichwa.strip()
                    palabra_existente.dificultad_juego = dificultad
                    palabra_existente.frecuencia_uso += 1
                    palabra_existente.save()
                    palabra = palabra_existente
                else:
                    # Crear nueva palabra
                    palabra = Palabra.objects.create(
                        palabra_kichwa=traduccion_kichwa.strip(),
                        traduccion_espanol=termino_espanol.strip(),
                        categoria=categoria,
                        definicion=descripcion_kichwa.strip(),
                        descripcion_juego_kichwa=descripcion_kichwa.strip(),
                        pronunciacion=f'[{traduccion_kichwa.strip()}]',
                        nivel_dificultad='basico',
                        dificultad_juego=dificultad,
                        apta_para_juegos=True,
                        activa=True,
                        frecuencia_uso=1,
                    )
                
                contador += 1
                if contador % 100 == 0:
                    self.stdout.write(f'Procesadas {contador} palabras español-kichwa para juegos...')
        
        self.stdout.write(f'Cargadas {contador} palabras español-kichwa para juegos')
