# Generated by Django 4.2.23 on 2025-07-16 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Palabra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra_kichwa', models.CharField(max_length=200, verbose_name='Palabra en Kichwa')),
                ('traduccion_espanol', models.CharField(max_length=200, verbose_name='Traducción en Español')),
                ('pronunciacion', models.CharField(blank=True, max_length=300, verbose_name='Pronunciación')),
                ('ejemplo_uso', models.TextField(blank=True, verbose_name='Ejemplo de uso')),
                ('notas_gramaticales', models.TextField(blank=True, verbose_name='Notas gramaticales')),
                ('dificultad', models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Medio'), ('dificil', 'Difícil')], default='facil', max_length=10, verbose_name='Dificultad')),
                ('tipo', models.CharField(choices=[('kichwa_espanol', 'Kichwa-Español'), ('espanol_kichwa', 'Español-Kichwa')], default='kichwa_espanol', max_length=20, verbose_name='Tipo')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('veces_vista', models.PositiveIntegerField(default=0, verbose_name='Veces vista')),
            ],
            options={
                'verbose_name': 'Palabra',
                'verbose_name_plural': 'Palabras',
                'ordering': ['palabra_kichwa'],
                'unique_together': {('palabra_kichwa', 'traduccion_espanol')},
            },
        ),
        migrations.CreateModel(
            name='HistorialBusqueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termino_busqueda', models.CharField(max_length=200, verbose_name='Término de búsqueda')),
                ('resultados_encontrados', models.IntegerField(default=0, verbose_name='Resultados encontrados')),
                ('fecha_busqueda', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de búsqueda')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de Búsqueda',
                'verbose_name_plural': 'Historial de Búsquedas',
                'ordering': ['-fecha_busqueda'],
            },
        ),
        migrations.CreateModel(
            name='EstadisticaJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_juego', models.CharField(choices=[('traduccion', 'Traducción'), ('completar', 'Completar'), ('memoria', 'Memoria'), ('conectar', 'Conectar')], max_length=20, verbose_name='Tipo de juego')),
                ('puntuacion', models.IntegerField(default=0, verbose_name='Puntuación')),
                ('tiempo_segundos', models.IntegerField(default=0, verbose_name='Tiempo en segundos')),
                ('respuestas_correctas', models.IntegerField(default=0, verbose_name='Respuestas correctas')),
                ('respuestas_incorrectas', models.IntegerField(default=0, verbose_name='Respuestas incorrectas')),
                ('nivel_dificultad', models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Medio'), ('dificil', 'Difícil')], default='facil', max_length=10, verbose_name='Nivel de dificultad')),
                ('completado', models.BooleanField(default=False, verbose_name='Completado')),
                ('fecha_juego', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del juego')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Estadística de Juego',
                'verbose_name_plural': 'Estadísticas de Juegos',
                'ordering': ['-fecha_juego'],
            },
        ),
        migrations.CreateModel(
            name='PalabraFavorita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregada', models.DateTimeField(auto_now_add=True, verbose_name='Fecha agregada')),
                ('palabra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diccionario.palabra', verbose_name='Palabra')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Palabra Favorita',
                'verbose_name_plural': 'Palabras Favoritas',
                'ordering': ['-fecha_agregada'],
                'unique_together': {('usuario', 'palabra')},
            },
        ),
    ]
