# Generated by Django 4.2.23 on 2025-07-16 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diccionario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadisticajuego',
            name='completado',
        ),
        migrations.RemoveField(
            model_name='estadisticajuego',
            name='nivel_dificultad',
        ),
        migrations.RemoveField(
            model_name='estadisticajuego',
            name='tiempo_segundos',
        ),
        migrations.RemoveField(
            model_name='historialbusqueda',
            name='termino_busqueda',
        ),
        migrations.AddField(
            model_name='estadisticajuego',
            name='dificultad',
            field=models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Medio'), ('dificil', 'Difícil')], default='facil', max_length=10),
        ),
        migrations.AddField(
            model_name='estadisticajuego',
            name='tiempo_jugado',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialbusqueda',
            name='termino_buscado',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estadisticajuego',
            name='fecha_juego',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='estadisticajuego',
            name='puntuacion',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estadisticajuego',
            name='respuestas_correctas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estadisticajuego',
            name='respuestas_incorrectas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estadisticajuego',
            name='tipo_juego',
            field=models.CharField(choices=[('traduccion', 'Traducción'), ('completar', 'Completar'), ('memoria', 'Memoria'), ('conectar', 'Conectar')], max_length=20),
        ),
        migrations.AlterField(
            model_name='estadisticajuego',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas_juegos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historialbusqueda',
            name='fecha_busqueda',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='historialbusqueda',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historialbusqueda',
            name='resultados_encontrados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historialbusqueda',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historial_busquedas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='palabra',
            name='dificultad',
            field=models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Medio'), ('dificil', 'Difícil')], default='facil', max_length=10),
        ),
        migrations.AlterField(
            model_name='palabra',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='palabra',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='palabra',
            name='tipo',
            field=models.CharField(choices=[('kichwa_espanol', 'Kichwa-Español'), ('espanol_kichwa', 'Español-Kichwa')], default='kichwa_espanol', max_length=20),
        ),
        migrations.AlterField(
            model_name='palabrafavorita',
            name='fecha_agregada',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='palabrafavorita',
            name='palabra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='diccionario.palabra'),
        ),
        migrations.AlterField(
            model_name='palabrafavorita',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palabras_favoritas', to=settings.AUTH_USER_MODEL),
        ),
    ]
