# Generated by Django 4.2.23 on 2025-07-16 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def convertir_tiempo_jugado_a_segundos(apps, schema_editor):
    """Convierte DurationField histórico a segundos sin romper PostgreSQL."""
    estadistica_juego = apps.get_model('diccionario', 'EstadisticaJuego')
    tabla = schema_editor.quote_name(estadistica_juego._meta.db_table)
    columna = schema_editor.quote_name('tiempo_jugado')

    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute(
            f'ALTER TABLE {tabla} ALTER COLUMN {columna} TYPE integer '
            f'USING EXTRACT(EPOCH FROM {columna})::integer'
        )
        return

    campo_anterior = estadistica_juego._meta.get_field('tiempo_jugado')
    campo_nuevo = models.IntegerField(default=0, help_text='Tiempo en segundos')
    campo_nuevo.set_attributes_from_name('tiempo_jugado')
    schema_editor.alter_field(estadistica_juego, campo_anterior, campo_nuevo)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diccionario', '0003_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialbusqueda',
            options={'ordering': ['-fecha_busqueda'], 'verbose_name': 'Historial de Búsqueda', 'verbose_name_plural': 'Historiales de Búsqueda'},
        ),
        migrations.AlterModelOptions(
            name='palabrafavorita',
            options={'verbose_name': 'Palabra Favorita', 'verbose_name_plural': 'Palabras Favoritas'},
        ),
        migrations.RenameField(
            model_name='estadisticajuego',
            old_name='respuestas_correctas',
            new_name='palabras_correctas',
        ),
        migrations.RenameField(
            model_name='estadisticajuego',
            old_name='respuestas_incorrectas',
            new_name='palabras_incorrectas',
        ),
        migrations.RenameField(
            model_name='historialbusqueda',
            old_name='termino_buscado',
            new_name='termino_busqueda',
        ),
        migrations.AlterUniqueTogether(
            name='palabra',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='estadisticajuego',
            name='dificultad',
        ),
        migrations.RemoveField(
            model_name='historialbusqueda',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='palabra',
            name='categoria',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='palabras', to='diccionario.categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='palabra',
            name='definicion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='palabra',
            name='etimologia',
            field=models.TextField(blank=True, help_text='Origen etimológico de la palabra'),
        ),
        migrations.AddField(
            model_name='palabra',
            name='sinonimos',
            field=models.TextField(blank=True, help_text='Sinónimos separados por comas'),
        ),
        migrations.AlterField(
            model_name='estadisticajuego',
            name='puntuacion',
            field=models.PositiveIntegerField(),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    convertir_tiempo_jugado_a_segundos,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='estadisticajuego',
                    name='tiempo_jugado',
                    field=models.IntegerField(default=0, help_text='Tiempo en segundos'),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='estadisticajuego',
            name='tipo_juego',
            field=models.CharField(choices=[('memoria', 'Juego de Memoria'), ('traduccion', 'Juego de Traducción'), ('completar', 'Completar Palabra'), ('conectar', 'Conectar Palabras')], max_length=20),
        ),
        migrations.AlterField(
            model_name='estadisticajuego',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historialbusqueda',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='palabra',
            name='dificultad',
            field=models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Medio'), ('dificil', 'Difícil')], default='medio', max_length=10),
        ),
        migrations.AlterField(
            model_name='palabra',
            name='ejemplo_uso',
            field=models.TextField(blank=True, help_text='Ejemplo de uso en contexto'),
        ),
        migrations.AlterField(
            model_name='palabra',
            name='palabra_kichwa',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='palabra',
            name='pronunciacion',
            field=models.CharField(blank=True, help_text='Pronunciación fonética', max_length=300),
        ),
        migrations.AlterField(
            model_name='palabra',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='palabra',
            name='traduccion_espanol',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='palabra',
            name='veces_vista',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='palabrafavorita',
            name='palabra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diccionario.palabra'),
        ),
        migrations.AlterField(
            model_name='palabrafavorita',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='palabra',
            unique_together={('palabra_kichwa', 'categoria')},
        ),
        migrations.RemoveField(
            model_name='palabra',
            name='activa',
        ),
        migrations.RemoveField(
            model_name='palabra',
            name='notas_gramaticales',
        ),
        migrations.RemoveField(
            model_name='palabra',
            name='tipo',
        ),
        migrations.CreateModel(
            name='PalabraJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_juego', models.CharField(choices=[('memoria', 'Juego de Memoria'), ('traduccion', 'Juego de Traducción'), ('completar', 'Completar Palabra'), ('conectar', 'Conectar Palabras')], max_length=20)),
                ('dificultad_juego', models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Medio'), ('dificil', 'Difícil')], max_length=10)),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('pistas', models.TextField(blank=True, help_text='Pistas adicionales para el juego')),
                ('opciones_incorrectas', models.TextField(blank=True, help_text='Opciones incorrectas separadas por comas')),
                ('palabra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diccionario.palabra')),
            ],
            options={
                'verbose_name': 'Palabra de Juego',
                'verbose_name_plural': 'Palabras de Juegos',
                'ordering': ['orden', 'palabra__palabra_kichwa'],
                'unique_together': {('palabra', 'tipo_juego')},
            },
        ),
    ]
