# Generated by Django 4.2.7 on 2025-07-20 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diccionario', '0004_alter_historialbusqueda_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialbusqueda',
            options={'ordering': ['-fecha_busqueda'], 'verbose_name': 'Historial de Búsqueda', 'verbose_name_plural': 'Historial de Búsquedas'},
        ),
        migrations.AlterModelOptions(
            name='palabrafavorita',
            options={'ordering': ['-fecha_agregada'], 'verbose_name': 'Palabra Favorita', 'verbose_name_plural': 'Palabras Favoritas'},
        ),
        migrations.RenameField(
            model_name='estadisticajuego',
            old_name='palabras_correctas',
            new_name='respuestas_correctas',
        ),
        migrations.RenameField(
            model_name='estadisticajuego',
            old_name='palabras_incorrectas',
            new_name='respuestas_totales',
        ),
        migrations.RenameField(
            model_name='historialbusqueda',
            old_name='termino_busqueda',
            new_name='termino_buscado',
        ),
        migrations.AlterUniqueTogether(
            name='palabra',
            unique_together={('palabra_kichwa', 'traduccion_espanol')},
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='slug',
        ),
        migrations.AddField(
            model_name='categoria',
            name='color',
            field=models.CharField(default='#007bff', help_text='Color en formato hexadecimal', max_length=7),
        ),
        migrations.AddField(
            model_name='estadisticajuego',
            name='dificultad',
            field=models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Medio'), ('dificil', 'Difícil')], default='medio', max_length=10),
        ),
        migrations.AddField(
            model_name='palabra',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='palabra',
            name='apta_para_juegos',
            field=models.BooleanField(default=False, help_text='Indica si esta palabra es apta para usar en juegos'),
        ),
        migrations.AddField(
            model_name='palabra',
            name='descripcion_juego_espanol',
            field=models.TextField(blank=True, help_text='Descripción específica para juegos en español'),
        ),
        migrations.AddField(
            model_name='palabra',
            name='descripcion_juego_kichwa',
            field=models.TextField(blank=True, help_text='Descripción específica para juegos en kichwa'),
        ),
        migrations.AddField(
            model_name='palabra',
            name='dificultad_juego',
            field=models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Medio'), ('dificil', 'Difícil')], default='medio', help_text='Dificultad específica para juegos', max_length=10),
        ),
        migrations.AddField(
            model_name='palabra',
            name='frecuencia_uso',
            field=models.PositiveIntegerField(default=1, help_text='Frecuencia de uso en juegos'),
        ),
        migrations.AddField(
            model_name='palabra',
            name='nivel_dificultad',
            field=models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='basico', max_length=20),
        ),
        migrations.AddField(
            model_name='palabra',
            name='notas_gramaticales',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='palabra',
            name='tipo',
            field=models.CharField(choices=[('sustantivo', 'Sustantivo'), ('verbo', 'Verbo'), ('adjetivo', 'Adjetivo'), ('adverbio', 'Adverbio'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
        migrations.AlterField(
            model_name='estadisticajuego',
            name='puntuacion',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estadisticajuego',
            name='tiempo_jugado',
            field=models.PositiveIntegerField(default=0, help_text='Tiempo en segundos'),
        ),
        migrations.AlterField(
            model_name='estadisticajuego',
            name='tipo_juego',
            field=models.CharField(choices=[('traduccion', 'Traducción'), ('completar', 'Completar Palabras'), ('memoria', 'Juego de Memoria'), ('conectar', 'Conectar Palabras')], max_length=20),
        ),
        migrations.AlterField(
            model_name='palabra',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diccionario.categoria'),
        ),
        migrations.AlterField(
            model_name='palabra',
            name='ejemplo_uso',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='palabra',
            name='pronunciacion',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.DeleteModel(
            name='PalabraJuego',
        ),
        migrations.RemoveField(
            model_name='palabra',
            name='slug',
        ),
    ]
