# Generated by Django 4.2.7 on 2025-07-20 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diccionario', '0005_campos_juegos_completos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='palabrafavorita',
            options={'verbose_name': 'Palabra Favorita', 'verbose_name_plural': 'Palabras Favoritas'},
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estadisticajuego',
            name='puntuacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estadisticajuego',
            name='respuestas_correctas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estadisticajuego',
            name='respuestas_totales',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estadisticajuego',
            name='tiempo_jugado',
            field=models.IntegerField(default=0, help_text='Tiempo en segundos'),
        ),
        migrations.AlterField(
            model_name='estadisticajuego',
            name='tipo_juego',
            field=models.CharField(choices=[('traduccion', 'Traducción'), ('completar', 'Completar Palabras'), ('memoria', 'Juego de Memoria'), ('conectar', 'Conectar Traducciones'), ('sopa_letras', 'Sopa de Letras')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historialbusqueda',
            name='resultados_encontrados',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='palabra',
            name='apta_para_juegos',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='palabra',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palabras', to='diccionario.categoria'),
        ),
        migrations.AlterField(
            model_name='palabra',
            name='definicion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='palabra',
            name='descripcion_juego_espanol',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='palabra',
            name='descripcion_juego_kichwa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='palabra',
            name='dificultad_juego',
            field=models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Medio'), ('dificil', 'Difícil')], default='medio', max_length=10),
        ),
        migrations.AlterField(
            model_name='palabra',
            name='ejemplo_uso',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='palabra',
            name='etimologia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='palabra',
            name='frecuencia_uso',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='palabra',
            name='nivel_dificultad',
            field=models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='basico', max_length=15),
        ),
        migrations.AlterField(
            model_name='palabra',
            name='notas_gramaticales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='palabra',
            name='palabra_kichwa',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='palabra',
            name='pronunciacion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='palabra',
            name='sinonimos',
            field=models.TextField(blank=True, help_text='Separar con comas', null=True),
        ),
        migrations.AlterField(
            model_name='palabra',
            name='tipo',
            field=models.CharField(choices=[('sustantivo', 'Sustantivo'), ('verbo', 'Verbo'), ('adjetivo', 'Adjetivo'), ('adverbio', 'Adverbio'), ('otro', 'Otro')], default='sustantivo', max_length=15),
        ),
        migrations.AlterField(
            model_name='palabra',
            name='traduccion_espanol',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='palabra',
            name='veces_vista',
            field=models.IntegerField(default=0),
        ),
    ]
