# Generated by Django 4.2.7 on 2025-07-20 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diccionario', '0006_agregar_campos_faltantes'),
    ]

    operations = [
    ]
