# Generated by Django 4.2.30 on 2026-09-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diccionario', '0013_alter_palabra_audio_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='palabra',
            index=models.Index(fields=['activa', 'palabra_kichwa'], name='palabra_busq_kichwa_idx'),
        ),
        migrations.AddIndex(
            model_name='palabra',
            index=models.Index(fields=['activa', 'traduccion_espanol'], name='palabra_busq_espanol_idx'),
        ),
        migrations.AddIndex(
            model_name='palabra',
            index=models.Index(fields=['activa', 'categoria', 'dificultad'], name='palabra_filtros_idx'),
        ),
        migrations.AddIndex(
            model_name='palabra',
            index=models.Index(fields=['activa', 'apta_para_juegos', 'dificultad_juego'], name='palabra_juegos_idx'),
        ),
    ]
