# Generated by Django 4.2.30 on 2026-09-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diccionario', '0015_postgresql_trigram_search_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palabra',
            name='palabra_kichwa',
            field=models.CharField(db_index=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='palabra',
            name='pronunciacion',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
