# Generated by Django 4.2.30 on 2026-09-06 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diccionario', '0016_ampliar_campos_lexicos'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelacionPalabra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('familia', 'Misma familia semántica'), ('sinonimo', 'Sinónimo o equivalente'), ('contraste', 'Contraste o antónimo'), ('contexto', 'Relacionado por contexto')], default='contexto', max_length=12)),
                ('nota', models.CharField(blank=True, max_length=160)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_destino', to='diccionario.palabra')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_origen', to='diccionario.palabra')),
            ],
            options={
                'verbose_name': 'Relación entre palabras',
                'verbose_name_plural': 'Relaciones entre palabras',
            },
        ),
        migrations.AddConstraint(
            model_name='relacionpalabra',
            constraint=models.UniqueConstraint(fields=('origen', 'destino', 'tipo'), name='relacion_palabra_unica'),
        ),
        migrations.AddConstraint(
            model_name='relacionpalabra',
            constraint=models.CheckConstraint(check=models.Q(('origen', models.F('destino')), _negated=True), name='relacion_palabra_distinta'),
        ),
    ]
