# Generated by Django 4.2.30 on 2026-09-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diccionario', '0017_relaciones_lexicas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['grupo', 'orden', 'nombre'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AddField(
            model_name='categoria',
            name='grupo',
            field=models.CharField(choices=[('entorno', 'Entorno natural'), ('personas', 'Personas y comunidad'), ('cotidiano', 'Vida cotidiana'), ('lengua', 'Lengua, tiempo y pensamiento'), ('acciones', 'Acciones y cualidades')], default='lengua', max_length=20),
        ),
        migrations.AddField(
            model_name='categoria',
            name='orden',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='palabra',
            name='busqueda_contenido',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='palabra',
            name='busqueda_espanol',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='palabra',
            name='busqueda_kichwa',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=300),
        ),
        migrations.AddField(
            model_name='palabra',
            name='clasificacion_confianza',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja; requiere revisión'), ('manual', 'Clasificación manual')], db_index=True, default='baja', max_length=10),
        ),
        migrations.AddField(
            model_name='palabra',
            name='clasificacion_motivo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
