# Generated by Django 4.2.30 on 2026-09-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diccionario', '0023_actividad_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadisticajuego',
            name='tipo_juego',
            field=models.CharField(choices=[('traduccion', 'Traducción'), ('escucha', 'Escucha'), ('completar', 'Completar Palabras'), ('memoria', 'Juego de Memoria'), ('conectar', 'Conectar Traducciones'), ('sopa_letras', 'Sopa de Letras')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sesionjuego',
            name='tipo_juego',
            field=models.CharField(choices=[('traduccion', 'Traducción'), ('escucha', 'Escucha'), ('completar', 'Completar Palabras'), ('memoria', 'Juego de Memoria'), ('conectar', 'Conectar Traducciones'), ('sopa_letras', 'Sopa de Letras')], max_length=20),
        ),
    ]
