# Generated by Django 4.2.30 on 2026-09-14 15:24

from django.conf import settings
from django.db import migrations, models
from django.db.models import F, Value
from django.db.models.functions import Concat
import django.db.models.deletion


def limpiar_equivalencias_automaticas(apps, schema_editor):
    Palabra = apps.get_model('diccionario', 'Palabra')
    Palabra.objects.using(schema_editor.connection.alias).alias(
        marcador=Concat(
            'palabra_kichwa', Value(' - '), 'traduccion_espanol',
            output_field=models.TextField(),
        ),
    ).filter(ejemplo_uso=F('marcador')).update(ejemplo_uso=None)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diccionario', '0024_agregar_juego_escucha'),
    ]

    operations = [
        migrations.CreateModel(
            name='EjemploUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oracion_kichwa', models.TextField(help_text='Oración en Kichwa revisada en contexto.')),
                ('traduccion_espanol', models.TextField(help_text='Traducción fiel de la oración completa.')),
                ('fuente', models.CharField(help_text='Obra, informante autorizado o autoría propia.', max_length=300)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado')], db_index=True, default='borrador', max_length=12)),
                ('fecha_revision', models.DateTimeField(blank=True, editable=False, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('palabra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejemplos_uso', to='diccionario.palabra')),
                ('revisado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ejemplo de uso',
                'verbose_name_plural': 'Ejemplos de uso',
                'ordering': ['id'],
            },
        ),
        migrations.RunPython(limpiar_equivalencias_automaticas, migrations.RunPython.noop),
    ]
