# Generated by Django 4.2.30 on 2026-09-15 00:40

from django.db import migrations, models


IMAGENES = (
    ('yaku', 'agua', 'img/vocabulario/yaku-agua.webp', 'Agua clara fluyendo entre piedras y plantas.'),
    ('wasi', 'casa', 'img/vocabulario/wasi-casa.webp', 'Casa acogedora rodeada de plantas y montañas.'),
    ('inti', 'sol', 'img/vocabulario/inti-sol.webp', 'Sol dorado sobre un paisaje verde.'),
    ('allku', 'perro', 'img/vocabulario/allku-perro.webp', 'Perro café y blanco de pie sobre el césped.'),
    ('misi', 'gato', 'img/vocabulario/misi-gato.webp', 'Gato gris sentado sobre una estera tejida.'),
    ('sisa', 'flor', 'img/vocabulario/sisa-flor.webp', 'Flor anaranjada con tallo y hojas verdes.'),
    ('mayu', 'río', 'img/vocabulario/mayu-rio.webp', 'Río ancho que recorre un valle verde.'),
    ('sacha', 'bosque', 'img/vocabulario/sacha-bosque.webp', 'Bosque verde con árboles, helechos y un sendero.'),
    ('atallpa', 'gallina', 'img/vocabulario/atallpa-gallina.webp', 'Gallina de plumaje café junto a granos de maíz.'),
    ('kuchi', 'cerdo', 'img/vocabulario/kuchi-cerdo.webp', 'Cerdo rosado de pie frente a una cerca.'),
    ('kinti', 'colibrí', 'img/vocabulario/kinti-colibri.webp', 'Colibrí verde y azul volando junto a una flor.'),
)


def asociar_imagenes(apps, schema_editor):
    Palabra = apps.get_model('diccionario', 'Palabra')
    EjemploUso = apps.get_model('diccionario', 'EjemploUso')
    db = schema_editor.connection.alias
    for kichwa, espanol, ruta, descripcion in IMAGENES:
        Palabra.objects.using(db).filter(
            palabra_kichwa=kichwa, traduccion_espanol=espanol, activa=True,
        ).update(
            imagen_vocabulario=ruta,
            descripcion_imagen=descripcion,
            credito_imagen='Ilustración original creada para este proyecto.',
        )
    EjemploUso.objects.using(db).filter(
        estado='publicado', revisado_por__isnull=False,
    ).update(tipo_revision='humana', nota_revision='Aprobado antes del registro del tipo de revisión.')


class Migration(migrations.Migration):

    dependencies = [
        ('diccionario', '0026_limpiar_puntos_terminales'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejemplouso',
            name='nota_revision',
            field=models.CharField(blank=True, editable=False, max_length=300),
        ),
        migrations.AddField(
            model_name='ejemplouso',
            name='tipo_revision',
            field=models.CharField(blank=True, choices=[('humana', 'Revisión editorial humana'), ('documental', 'Cotejo documental con la fuente')], editable=False, max_length=12),
        ),
        migrations.AddField(
            model_name='palabra',
            name='credito_imagen',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='palabra',
            name='descripcion_imagen',
            field=models.CharField(blank=True, help_text='Descripción accesible de la ilustración.', max_length=240),
        ),
        migrations.AddField(
            model_name='palabra',
            name='imagen_vocabulario',
            field=models.CharField(blank=True, help_text='Ruta dentro de archivos estáticos para una ilustración de esta acepción.', max_length=200),
        ),
        migrations.RunPython(asociar_imagenes, migrations.RunPython.noop),
    ]
