# Generated by Django 4.2.30 on 2026-09-15 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


TIPO_POR_CATEGORIA = {
    'animales': 'ser_vivo',
    'plantas-y-agricultura': 'ser_vivo',
    'cuerpo-y-salud': 'objeto',
    'alimentos-y-bebidas': 'objeto',
    'hogar-y-construccion': 'objeto',
    'vestimenta-y-cuidado-personal': 'objeto',
    'herramientas-y-objetos': 'objeto',
    'transporte-y-caminos': 'objeto',
    'naturaleza-y-clima': 'paisaje',
    'territorio-y-lugares': 'paisaje',
    'familia-y-relaciones': 'persona',
    'personas-oficios-y-educacion': 'persona',
    'acciones-y-procesos': 'accion',
    'emociones-y-cualidades': 'cualidad',
    'numeros-cantidades-y-medidas': 'diagrama',
    'espacio-y-ubicacion': 'diagrama',
    'tiempo-y-calendario': 'diagrama',
    'ideas-y-conceptos': 'diagrama',
    'gramatica-y-expresiones': 'no_recomendada',
    'cultura-y-espiritualidad': 'diagrama',
}


def clasificar_acepciones(apps, schema_editor):
    Palabra = apps.get_model('diccionario', 'Palabra')
    Preparacion = apps.get_model('diccionario', 'PreparacionImagenVocabulario')
    db = schema_editor.connection.alias
    preparaciones = []
    palabras = Palabra.objects.using(db).select_related('categoria').all()
    for palabra in palabras.iterator(chunk_size=500):
        publicada = bool(palabra.imagen_vocabulario)
        preparaciones.append(Preparacion(
            palabra_id=palabra.pk,
            tipo_visual=TIPO_POR_CATEGORIA.get(palabra.categoria.slug, 'no_recomendada'),
            estado='publicada' if publicada else 'clasificada',
            ruta_candidata=palabra.imagen_vocabulario,
            descripcion_candidata=palabra.descripcion_imagen,
            credito_candidato=(
                palabra.credito_imagen or 'Ilustración original creada para este proyecto.'
            ),
        ))
    Preparacion.objects.using(db).bulk_create(preparaciones, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diccionario', '0027_imagenes_y_revision_documental'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreparacionImagenVocabulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_visual', models.CharField(choices=[('ser_vivo', 'Animal o planta'), ('objeto', 'Objeto o elemento concreto'), ('paisaje', 'Lugar, naturaleza o clima'), ('persona', 'Persona, familia u oficio'), ('accion', 'Acción representada en una escena'), ('cualidad', 'Cualidad o emoción'), ('diagrama', 'Concepto que requiere diagrama'), ('no_recomendada', 'Imagen no recomendada')], db_index=True, max_length=16)),
                ('estado', models.CharField(choices=[('clasificada', 'Clasificada'), ('preparada', 'Prompt preparado'), ('generada', 'Imagen generada'), ('revisada', 'Revisada'), ('publicada', 'Publicada'), ('descartada', 'Descartada')], db_index=True, default='clasificada', max_length=12)),
                ('lote', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('orden_lote', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('prompt', models.TextField(blank=True)),
                ('ruta_candidata', models.CharField(blank=True, help_text='Ruta estática de la imagen generada; todavía no se muestra al público.', max_length=300)),
                ('descripcion_candidata', models.CharField(blank=True, help_text='Texto alternativo que debe comprobarse antes de publicar.', max_length=240)),
                ('credito_candidato', models.CharField(blank=True, default='Ilustración original creada para este proyecto.', max_length=240)),
                ('notas_revision', models.CharField(blank=True, max_length=300)),
                ('fecha_revision', models.DateTimeField(blank=True, editable=False, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('palabra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preparacion_imagen', to='diccionario.palabra')),
                ('revisada_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preparación de imagen de vocabulario',
                'verbose_name_plural': 'Preparación de imágenes de vocabulario',
                'ordering': ['lote', 'orden_lote', 'palabra__palabra_kichwa'],
                'indexes': [models.Index(fields=['estado', 'tipo_visual'], name='imagen_estado_tipo_idx'), models.Index(fields=['lote', 'orden_lote'], name='imagen_lote_orden_idx')],
            },
        ),
        migrations.RunPython(clasificar_acepciones, migrations.RunPython.noop),
    ]
