# Generated by Django 4.2.30 on 2026-09-15 01:18

from django.db import migrations, models
import django.db.models.deletion


def marcar_imagenes_originales(apps, schema_editor):
    Palabra = apps.get_model('diccionario', 'Palabra')
    Preparacion = apps.get_model('diccionario', 'PreparacionImagenVocabulario')
    db = schema_editor.connection.alias
    Palabra.objects.using(db).exclude(imagen_vocabulario='').update(proveedor_imagen='original')
    Preparacion.objects.using(db).filter(
        estado='publicada', ruta_candidata__gt='',
    ).update(proveedor_candidato='original')


class Migration(migrations.Migration):

    dependencies = [
        ('diccionario', '0028_preparacionimagenvocabulario'),
    ]

    operations = [
        migrations.AddField(
            model_name='palabra',
            name='autor_imagen',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='palabra',
            name='autor_imagen_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='palabra',
            name='fuente_imagen_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='palabra',
            name='proveedor_imagen',
            field=models.CharField(blank=True, choices=[('original', 'Ilustración original'), ('pexels', 'Fotografía de Pexels')], max_length=12),
        ),
        migrations.AddField(
            model_name='preparacionimagenvocabulario',
            name='autor_candidato',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='preparacionimagenvocabulario',
            name='autor_candidato_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='preparacionimagenvocabulario',
            name='fuente_candidata_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='preparacionimagenvocabulario',
            name='proveedor_candidato',
            field=models.CharField(blank=True, choices=[('original', 'Ilustración original'), ('pexels', 'Fotografía de Pexels')], max_length=12),
        ),
        migrations.CreateModel(
            name='CandidataImagenPexels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pexels_id', models.PositiveBigIntegerField()),
                ('orden', models.PositiveSmallIntegerField()),
                ('url_foto', models.URLField(max_length=500)),
                ('url_imagen', models.URLField(max_length=1000)),
                ('fotografo', models.CharField(max_length=200)),
                ('url_fotografo', models.URLField(max_length=500)),
                ('descripcion_original', models.CharField(blank=True, max_length=500)),
                ('ancho', models.PositiveIntegerField()),
                ('alto', models.PositiveIntegerField()),
                ('color_promedio', models.CharField(blank=True, max_length=7)),
                ('seleccionada', models.BooleanField(db_index=True, default=False)),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
                ('preparacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatas_pexels', to='diccionario.preparacionimagenvocabulario')),
            ],
            options={
                'verbose_name': 'Candidata de Pexels',
                'verbose_name_plural': 'Candidatas de Pexels',
                'ordering': ['preparacion__lote', 'preparacion__orden_lote', 'orden'],
            },
        ),
        migrations.AddConstraint(
            model_name='candidataimagenpexels',
            constraint=models.UniqueConstraint(fields=('preparacion', 'pexels_id'), name='pexels_unica_por_acepcion'),
        ),
        migrations.AddConstraint(
            model_name='candidataimagenpexels',
            constraint=models.UniqueConstraint(condition=models.Q(('seleccionada', True)), fields=('preparacion',), name='pexels_una_seleccionada'),
        ),
        migrations.RunPython(marcar_imagenes_originales, migrations.RunPython.noop),
    ]
