# Generated by Django 4.2.30 on 2026-09-15 13:22

from django.db import migrations, models


def preparar_contenido_ingles(apps, schema_editor):
    Categoria = apps.get_model('diccionario', 'Categoria')
    Palabra = apps.get_model('diccionario', 'Palabra')
    categorias = {
        'Animales': ('Animals', 'Domestic and wild animals, insects, birds, fish, and their body parts.'),
        'Cuerpo y salud': ('Body and health', 'Body parts, senses, illnesses, medicine, and wellbeing.'),
        'Gramática y expresiones': ('Grammar and expressions', 'Pronouns, particles, connectors, interjections, and expressions.'),
        'Naturaleza y clima': ('Nature and weather', 'Water, sky, weather, natural phenomena, and elements of the environment.'),
        'Plantas y agricultura': ('Plants and agriculture', 'Plants, trees, flowers, seeds, crops, sowing, and harvesting.'),
        'Tiempo y calendario': ('Time and calendar', 'Times of day, dates, duration, cycles, and the calendar.'),
        'Territorio y lugares': ('Land and places', 'Landforms, rivers, roads, regions, spaces, and geographical places.'),
        'Familia y relaciones': ('Family and relationships', 'Kinship, life stages, and emotional or social relationships.'),
        'Personas, oficios y educación': ('People, work, and education', 'People, community roles, professions, authorities, and learning.'),
        'Cultura y espiritualidad': ('Culture and spirituality', 'Worldview, ceremonies, music, art, community, and ancestral knowledge.'),
        'Alimentos y bebidas': ('Food and drinks', 'Foods, fruits, vegetables, drinks, ingredients, and preparations.'),
        'Hogar y construcción': ('Home and building', 'Homes, domestic spaces, furniture, and building elements.'),
        'Vestimenta y cuidado personal': ('Clothing and personal care', 'Clothing, footwear, accessories, and personal care items.'),
        'Herramientas y objetos': ('Tools and objects', 'Utensils, containers, materials, instruments, and everyday objects.'),
        'Transporte y caminos': ('Transport and roads', 'Vehicles, travel, routes, and means of transport.'),
        'Números, cantidades y medidas': ('Numbers, quantities, and measurements', 'Numbers, quantities, sizes, weights, distances, and units of measurement.'),
        'Espacio y ubicación': ('Space and location', 'Positions, directions, orientation, and spatial relationships.'),
        'Ideas y conceptos': ('Ideas and concepts', 'Abstract concepts that do not reliably belong to another topic.'),
        'Acciones y procesos': ('Actions and processes', 'Verbs, movements, changes, and activities.'),
        'Emociones y cualidades': ('Emotions and qualities', 'Emotions, states, colors, shapes, and descriptive characteristics.'),
    }
    for nombre, (nombre_ingles, descripcion_ingles) in categorias.items():
        Categoria.objects.filter(nombre=nombre).update(
            nombre_ingles=nombre_ingles,
            descripcion_ingles=descripcion_ingles,
        )

    vocabulario_inicial = {
        'yaku': 'water',
        'wasi': 'house',
        'inti': 'sun',
        'allku': 'dog',
        'misi': 'cat',
        'sisa': 'flower',
        'mayu': 'river',
        'sacha': 'forest',
        'atallpa': 'chicken',
        'kuchi': 'pig',
        'kinti': 'hummingbird',
    }
    for palabra_kichwa, traduccion_ingles in vocabulario_inicial.items():
        Palabra.objects.filter(
            palabra_kichwa__iexact=palabra_kichwa,
            activa=True,
        ).update(
            traduccion_ingles=traduccion_ingles,
            busqueda_ingles=traduccion_ingles,
            estado_revision_ingles='validada',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('diccionario', '0029_palabra_autor_imagen_palabra_autor_imagen_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descripcion_ingles',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='nombre_ingles',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='palabra',
            name='busqueda_ingles',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='palabra',
            name='definicion_ingles',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='palabra',
            name='estado_revision_ingles',
            field=models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('revisada', 'Revisada'), ('validada', 'Validada')], db_index=True, default='pendiente', help_text='Solo las traducciones inglesas validadas se muestran al público.', max_length=10),
        ),
        migrations.AddField(
            model_name='palabra',
            name='traduccion_ingles',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.RunPython(preparar_contenido_ingles, migrations.RunPython.noop),
    ]
