# Generated by Django 4.2.23 on 2025-07-16 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('biografia', models.TextField(blank=True, max_length=500, verbose_name='Biografía')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('N', 'Prefiero no decir')], max_length=1, verbose_name='Género')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('pais', models.CharField(blank=True, max_length=100, verbose_name='País')),
                ('nivel_kichwa', models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado'), ('nativo', 'Hablante nativo')], default='principiante', max_length=20, verbose_name='Nivel de Kichwa')),
                ('palabras_aprendidas', models.PositiveIntegerField(default=0, verbose_name='Palabras aprendidas')),
                ('puntos_totales', models.PositiveIntegerField(default=0, verbose_name='Puntos totales')),
                ('racha_dias', models.PositiveIntegerField(default=0, verbose_name='Racha de días')),
                ('notificaciones_email', models.BooleanField(default=True, verbose_name='Notificaciones por email')),
                ('perfil_publico', models.BooleanField(default=False, verbose_name='Perfil público')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('ultima_actividad', models.DateTimeField(auto_now=True, verbose_name='Última actividad')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
