# Generated by Django 4.2.23 on 2025-07-16 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='biografia',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='nivel_kichwa',
            field=models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado'), ('nativo', 'Nativo')], default='principiante', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='notificaciones_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='pais',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='palabras_aprendidas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='perfil_publico',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='puntos_totales',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='racha_dias',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='ultima_actividad',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
    ]
