"""Genera el catálogo inglés de Django sin depender de gettext del sistema."""

from __future__ import annotations

import json
import struct
from pathlib import Path


TRANSLATIONS = {
    'Saltar al contenido principal': 'Skip to main content',
    'Navegación principal': 'Main navigation',
    'Inicio': 'Home', 'Buscar': 'Search', 'Juegos': 'Games',
    'Mi perfil': 'My profile', 'Mis favoritas': 'My favorites',
    'Cerrar sesión': 'Sign out', 'Iniciar sesión': 'Sign in', 'Registrarse': 'Register',
    'Idioma de la interfaz': 'Interface language', 'Cerrar mensaje': 'Close message', 'Cerrar': 'Close',
    'Guarda tus palabras favoritas': 'Save your favorite words',
    'Para guardar palabras necesitas iniciar sesión o crear una cuenta.': 'To save words, sign in or create an account.',
    'Consulta un corpus bilingüe Kichwa, escucha pronunciaciones disponibles y guarda palabras para continuar aprendiendo.': 'Browse a bilingual Kichwa corpus, listen to available pronunciations, and save words to keep learning.',
    'Enlaces rápidos': 'Quick links', 'Buscar palabras': 'Search words', 'Información': 'Information',
    'Términos de uso': 'Terms of use', 'Política de privacidad': 'Privacy policy',
    'Tu diccionario digital.': 'Your digital dictionary.',
    'Preservando y promoviendo la lengua Kichwa': 'Preserving and promoting the Kichwa language',
    'Corpus en curación continua': 'Corpus under continuous review', 'Comunidad activa': 'Active community',
    'Hecho con amor': 'Made with care',
    'Diccionario Kichwa | Busca, comprende y aprende': 'Kichwa Dictionary | Search, understand, and learn',
    'Encuentra una palabra en Kichwa, español o inglés': 'Find a word in Kichwa, Spanish, or English',
    'Consulta equivalencias, pronunciación y contexto en un corpus de %(total_palabras)s entradas organizado por temas reales.': 'Browse meanings, pronunciation, and context in a corpus of %(total_palabras)s entries organized by practical topics.',
    '¿Qué palabra quieres comprender?': 'Which word would you like to understand?',
    'Prueba con wasi, casa, water o yaku': 'Try wasi, casa, water, or yaku',
    'Escribe una palabra completa o una parte, en Kichwa o español': 'Enter a full word or part of one, in Kichwa or Spanish',
    'Tema': 'Topic', 'Todos los temas': 'All topics', 'Pronunciación': 'Pronunciation',
    'Cualquier dificultad': 'Any difficulty', 'Fácil': 'Easy', 'Media': 'Medium', 'Difícil': 'Hard',
    'Abrir esta entrada': 'Open this entry', 'entradas del corpus': 'corpus entries',
    'temas para explorar': 'topics to explore', 'juegos de práctica': 'practice games',
    'Explorar el corpus': 'Explore the corpus', 'Reto de esta semana': "This week's challenge",
    'Acierta cinco palabras distintas en <strong>%(modalidad)s</strong>. El reto cambia cada lunes.': 'Answer five different words correctly in <strong>%(modalidad)s</strong>. The challenge changes every Monday.',
    'Reto completado': 'Challenge completed', '%(avance)s de %(meta)s palabras': '%(avance)s of %(meta)s words',
    'Tu avance es privado y se reinicia cada lunes.': 'Your progress is private and resets every Monday.',
    'Juega sin cuenta.': 'Play without an account.', 'Inicia sesión': 'Sign in', 'para guardar tu avance.': 'to save your progress.',
    'Volver a practicar': 'Practice again', 'Empezar reto': 'Start challenge',
    'Explora por tema': 'Explore by topic',
    'Resumen del diccionario': 'Dictionary summary', 'Ver los %(total_categorias)s temas': 'View all %(total_categorias)s topics',
    'Empieza por un campo cotidiano y continúa descubriendo vocabulario relacionado.': 'Start with an everyday topic and continue discovering related vocabulary.',
    'Aprender en comunidad': 'Learn with the community',
    'Descubre el progreso compartido y las entradas que más curiosidad despiertan esta semana.': 'Discover shared progress and the entries attracting the most interest this week.',
    'Ranking de aprendizaje': 'Learning ranking',
    '10 puntos por cada palabra acertada por primera vez.': '10 points for each word answered correctly for the first time.',
    'Más buscadas de la semana': 'Most searched this week',
    'Crea una cuenta para sumar puntos': 'Create an account to earn points', 'Explorar palabras': 'Explore words',
    'Consultas exactas de los últimos siete días; aquí solo mostramos conteos.': 'Exact searches from the last seven days; only totals are shown here.',
    'Palabras para seguir aprendiendo': 'Words to keep learning',
    'Una selección variada y estable de distintas áreas del diccionario.': 'A varied, stable selection from different areas of the dictionary.',
    'Ver entrada': 'View entry', 'Aprende una palabra y úsala': 'Learn a word and use it',
    'Busca su significado, escucha la pronunciación y llévala a uno de los juegos.': 'Look up its meaning, listen to its pronunciation, and practice it in a game.',
    'Ir a los juegos': 'Go to games',
    'Buscar en Kichwa, español e inglés | Diccionario Kichwa': 'Search Kichwa, Spanish, and English | Kichwa Dictionary',
    'Busca en Kichwa, español o inglés': 'Search in Kichwa, Spanish, or English',
    'Escribe una palabra en cualquiera de los idiomas disponibles. Puedes combinar la búsqueda con un tema y la dificultad de pronunciación.': 'Enter a word in any available language. You can combine the search with a topic and pronunciation difficulty.',
    'Explorar los 20 temas': 'Explore the 20 topics', '¿Qué palabra buscas?': 'Which word are you looking for?',
    'Palabra en Kichwa, español o inglés': 'Word in Kichwa, Spanish, or English',
    'Ejemplo: wasi, casa, yaku o water': 'Example: wasi, casa, yaku, or water',
    'La búsqueda reconoce mayúsculas y palabras con o sin tilde.': 'Search ignores letter case and recognizes words with or without accent marks.',
    'Afinar resultados': 'Refine results', 'Limpiar': 'Clear', 'Dificultad de pronunciación': 'Pronunciation difficulty',
    'Limita los resultados a un tema del diccionario': 'Limit results to one dictionary topic',
    'Aplicar filtros': 'Apply filters', 'Resultados para “%(query)s”': 'Results for “%(query)s”',
    'Palabras filtradas': 'Filtered words', 'Todas las palabras': 'All words',
    'Anterior': 'Previous', 'Página <strong>%(actual)s</strong> de %(total)s': 'Page <strong>%(actual)s</strong> of %(total)s',
    'Siguiente': 'Next', 'No encontramos una coincidencia': 'No match found',
    'Prueba con la palabra en otro idioma, revisa la escritura o elimina alguno de los filtros.': 'Try the word in another language, check its spelling, or remove a filter.',
    'Ver todo el diccionario': 'View the full dictionary',
    'Vocabulario organizado por temas': 'Vocabulary organized by topic',
    'Las categorías reúnen palabras por su significado: animales con animales, alimentos con alimentos y acciones con acciones.': 'Categories group words by meaning: animals with animals, foods with foods, and actions with actions.',
    'Ir al buscador': 'Go to search', 'Explorar': 'Explore', 'Abrir con filtros': 'Open with filters',
    'Palabras del tema': 'Words in this topic',
    'Definición': 'Definition',
    'La traducción inglesa de esta entrada sigue pendiente de revisión; se muestra la equivalencia en español.': 'The English translation for this entry is still under review; the Spanish equivalent is shown.',
    '<strong>%(kichwa)s</strong> se traduce al %(idioma)s como <strong>%(traduccion)s</strong>. Esta entrada todavía no tiene una definición ampliada.': '<strong>%(kichwa)s</strong> translates into %(idioma)s as <strong>%(traduccion)s</strong>. This entry does not have an expanded definition yet.',
    'En contexto': 'In context', 'Fuente': 'Source', 'Cotejado con la fuente citada': 'Checked against the cited source',
    'Ficha rápida': 'Quick facts', 'Idioma de entrada': 'Entry language', 'Consultas': 'Views',
    'Continúa aprendiendo': 'Keep learning', 'Practicar en juegos': 'Practice in games',
    'Buscar otra palabra': 'Search another word', 'Ver este tema': 'View this topic',
    'Guardada en favoritas': 'Saved to favorites', 'Guardar en favoritas': 'Save to favorites',
    'Palabras relacionadas': 'Related words',
    'Sugerencias basadas en relaciones editoriales, significado y contexto; no se completan al azar.': 'Suggestions based on editorial relationships, meaning, and context; they are not filled at random.',
    'Practicar Kichwa - Diccionario Kichwa': 'Practice Kichwa - Kichwa Dictionary',
    'Practica palabras con un propósito': 'Practice words with a purpose',
    'Reconoce, escucha y produce vocabulario en Kichwa. Cada partida respeta el tema y la dificultad que elijas.': 'Recognize, listen to, and produce Kichwa vocabulary. Every game follows your chosen topic and difficulty.',
    'palabras practicadas': 'words practiced', 'dominadas': 'mastered', 'precisión acumulada': 'overall accuracy',
    'Practica sin cuenta.': 'Practice without an account.',
    'Al iniciar sesión, guardaremos el avance de cada palabra para proponerte lo que necesitas reforzar.': 'When you sign in, we save each word’s progress so you can focus on what needs practice.',
    'Una ruta, seis habilidades': 'One path, six skills',
    'Empieza por reconocer y continúa cuando quieras. No necesitas completar una modalidad para abrir la siguiente.': 'Start with recognition and continue whenever you like. You do not need to complete one mode to open the next.',
    'Empezar a reconocer': 'Start recognizing', 'Abrir modalidad': 'Open mode',
    'Reconocer': 'Recognize', 'Traducción guiada': 'Guided translation',
    'Reconoce equivalencias en ambos sentidos y aprende a distinguir significados cercanos.': 'Recognize equivalent words in both directions and learn to distinguish similar meanings.',
    'Escuchar': 'Listen', 'Escucha y reconoce': 'Listen and recognize',
    'Escucha una grabación de Kichwa y elige su significado.': 'Listen to a Kichwa recording and choose its meaning.',
    'Asociar': 'Match', 'Conectar significados': 'Match meanings',
    'Une cada palabra Kichwa con su significado mediante selecciones claras.': 'Match each Kichwa word with its meaning through clear selections.',
    'Recordar': 'Remember', 'Memoria bilingüe': 'Bilingual memory',
    'Recupera parejas del mismo tema y fortalece el recuerdo visual del vocabulario.': 'Find pairs from the same topic and strengthen your visual memory of vocabulary.',
    'Producir': 'Produce', 'Completar en Kichwa': 'Complete in Kichwa',
    'Escribe la palabra completa a partir de su significado y una pista gradual.': 'Write the complete word from its meaning and a gradual hint.',
    'Sopa de palabras': 'Word search',
    'Localiza vocabulario en horizontal, vertical y diagonal, también en sentido inverso.': 'Find vocabulary horizontally, vertically, and diagonally, including backwards.',
    'Practicar Kichwa': 'Practice Kichwa', 'Ruta de práctica': 'Practice path', 'Dificultad': 'Difficulty',
    'Avance de la partida': 'Game progress', 'Pregunta 1 de %(total_palabras)s': 'Question 1 of %(total_palabras)s',
    'Usar pista': 'Use hint', 'Omitir palabra': 'Skip word', 'Sesión terminada': 'Session complete',
    'Practicar otra vez': 'Practice again', 'Elegir otra modalidad': 'Choose another mode',
    'Efectos activados': 'Sound effects on', 'Aciertos': 'Correct', 'Racha': 'Streak', 'Tiempo': 'Time',
    '¿Necesitas dos pistas más?': 'Need two more hints?',
    'Inicia sesión o crea una cuenta. Son dos pistas extra por cuenta, disponibles una sola vez entre todos los juegos. Al acceder, esta partida anónima comenzará de nuevo.': 'Sign in or create an account. Each account gets two extra hints, available once across all games. After signing in, this anonymous game will restart.',
    'Datos de la sesión': 'Session details', 'Pistas disponibles': 'Available hints',
    'Esta partida funciona sin cuenta.': 'This game works without an account.',
    'para conservar el progreso de cada palabra.': 'to save progress for each word.',
    '¿Quieres salir de la partida?': 'Do you want to leave the game?',
    'El avance ya respondido se conserva, pero esta sesión quedará incompleta.': 'Answered progress is saved, but this session will remain incomplete.',
    'Continuar jugando': 'Keep playing', 'Salir de la partida': 'Leave game',
    'Cómo se practica': 'How to practice', 'Responde y revisa la explicación antes de continuar.': 'Answer and review the explanation before continuing.',
    'Reconoce equivalencias en Kichwa y el idioma seleccionado con opciones del mismo conjunto temático.': 'Recognize equivalent words in Kichwa and the selected language using options from the same topic.',
    'Lee la palabra y elige su equivalencia. La dirección cambia para practicar ambos idiomas.': 'Read the word and choose its equivalent. The direction changes so you practice both languages.',
    'Escucha grabaciones del corpus y reconoce su significado.': 'Listen to corpus recordings and recognize their meaning.',
    'Pulsa Escuchar y elige el significado. Puedes escuchar más despacio o abrir la transcripción si necesitas leerla.': 'Press Listen and choose the meaning. You can slow the audio down or open the transcript if you need to read it.',
    'Recupera la escritura Kichwa a partir del significado y de letras visibles.': 'Recall the Kichwa spelling from its meaning and visible letters.',
    'Escribe la palabra completa. Puedes pedir una letra adicional; tildes editoriales y mayúsculas no cambian la validación.': 'Write the complete word. You can request another letter; editorial accent marks and capitalization do not change validation.',
    'Encuentra cada pareja bilingüe y refuerza el recuerdo visual.': 'Find each bilingual pair and strengthen visual recall.',
    'Abre dos fichas. Una pareja correcta comparte el mismo significado; las fichas incorrectas vuelven a cerrarse.': 'Open two cards. A correct pair shares the same meaning; incorrect cards close again.',
    'Asocia las dos columnas por selección: funciona con teclado, ratón y pantalla táctil.': 'Match the two columns by selecting items; it works with keyboard, mouse, and touch.',
    'Elige primero una palabra Kichwa y después su significado. No necesitas arrastrar ni dibujar líneas.': 'Choose a Kichwa word first, then its meaning. You do not need to drag or draw lines.',
    'Localiza vocabulario Kichwa y relaciona cada forma escrita con su significado.': 'Find Kichwa vocabulary and connect each written form with its meaning.',
    'Arrastra desde la primera hasta la última letra en horizontal, vertical o diagonal. También puedes marcar ambos extremos con dos toques o usar el teclado.': 'Drag from the first to the last letter horizontally, vertically, or diagonally. You can also tap both ends or use the keyboard.',
    'Palabras que guardaste': 'Words you saved',
    'Tu colección privada para volver a escuchar, leer y practicar Kichwa.': 'Your private collection for listening, reading, and practicing Kichwa again.',
    'Mi actividad': 'My activity',
    'Tu actividad es privada. Solo tú y el personal administrador autorizado pueden verla.': 'Your activity is private. Only you and authorized administrators can view it.',
    'Registro privado': 'Private record', 'Últimos 30 días': 'Last 30 days',
    'Resumen de tu uso, no de otras personas.': 'A summary of your use, not anyone else’s.',
    'Búsquedas': 'Searches', 'Entradas vistas': 'Entries viewed', 'Partidas terminadas': 'Games completed',
    'Minutos de juego': 'Minutes played', 'Aciertos en juegos': 'Correct answers in games',
    'Historial': 'History', 'De más reciente a más antiguo': 'Most recent first',
    'Volver a la entrada': 'Return to entry', 'Entrada ya no disponible': 'Entry no longer available',
    'Iniciar sesión | Diccionario Kichwa': 'Sign in | Kichwa Dictionary',
    'Tu aprendizaje continúa aquí.': 'Your learning continues here.',
    'Inicia sesión para conservar tus favoritas y consultar tu progreso desde una cuenta personal.': 'Sign in to keep your favorites and view your progress from your personal account.',
    'Guarda palabras para volver a ellas.': 'Save words to revisit them.',
    'Conserva tu progreso en los juegos.': 'Keep your game progress.',
    'Puedes usar tu nombre de usuario o el correo asociado a la cuenta.': 'You can use your username or the email linked to your account.',
    'Usuario o correo electrónico': 'Username or email', 'Contraseña': 'Password',
    '¿La olvidaste?': 'Forgot it?', 'Entrar a mi cuenta': 'Open my account',
    'Si compartes el dispositivo, cierra la sesión al terminar. Nunca envíes tu contraseña por correo.': 'If you share this device, sign out when you finish. Never send your password by email.',
    '¿Aún no tienes una cuenta?': 'Do not have an account yet?', 'Crear una cuenta': 'Create an account',
    'Crear una cuenta | Diccionario Kichwa': 'Create an account | Kichwa Dictionary',
    'Crea tu espacio de aprendizaje.': 'Create your learning space.',
    'Los datos obligatorios permiten identificar tu cuenta y recuperarla. La información del perfil puede completarse después.': 'Required information identifies your account and lets you recover it. You can complete profile information later.',
    'Crear cuenta': 'Create account',
    'Todos los campos de esta sección son obligatorios, excepto las novedades educativas.': 'All fields in this section are required except educational updates.',
    'Nombre': 'First name', 'Apellido': 'Last name', 'Nombre de usuario': 'Username',
    'Correo electrónico': 'Email address', 'Confirmar contraseña': 'Confirm password',
    'He leído y acepto los': 'I have read and accept the', 'y la': 'and the',
    'La aceptación es necesaria para crear la cuenta.': 'Acceptance is required to create the account.',
    'Quiero recibir novedades educativas por correo. Puedo cambiar esta preferencia desde mi perfil.': 'I want to receive educational updates by email. I can change this preference in my profile.',
    'Crear mi cuenta': 'Create my account', '¿Ya tienes una cuenta?': 'Already have an account?',
    'Tu espacio personal': 'Your personal space', 'Perfil de la comunidad': 'Community profile',
    'Editar perfil': 'Edit profile', 'Tu recorrido': 'Your journey',
    'Aprender, palabra a palabra': 'Learn, word by word', 'Continuar practicando': 'Continue practicing',
    'Puntos ganados': 'Points earned', 'Palabras practicadas': 'Words practiced',
    'Palabras dominadas': 'Words mastered', 'Aciertos al practicar': 'Practice accuracy',
    'Misiones de práctica': 'Practice missions',
    'Sigue objetivos concretos mientras practicas. Los puntos se ganan al acertar una palabra por primera vez.': 'Follow concrete goals as you practice. Points are earned when you answer a word correctly for the first time.',
    'Siguiente paso': 'Next step', 'Sigue explorando el Kichwa': 'Keep exploring Kichwa',
    'Practica en seis modalidades o vuelve a una palabra guardada para repasarla.': 'Practice in six modes or revisit a saved word for review.',
    'Actividad reciente': 'Recent activity', 'Ver historial completo': 'View full history',
    'Ayuda para practicar': 'Practice help', 'Pistas extra': 'Extra hints', 'Tu colección': 'Your collection',
    'Palabras favoritas': 'Favorite words', 'Ver mis favoritas': 'View my favorites',
    'A tu elección': 'Your choice', 'Privacidad y cuenta': 'Privacy and account',
    'Cambiar preferencias': 'Change preferences', 'Cambiar contraseña': 'Change password',
    'Ver actividad y estadísticas': 'View activity and statistics',
    'Entorno natural': 'Natural environment', 'Personas y comunidad': 'People and community',
    'Vida cotidiana': 'Everyday life', 'Lengua, tiempo y pensamiento': 'Language, time, and thought',
    'Acciones y cualidades': 'Actions and qualities',
    'Efectos silenciados': 'Sound effects muted', 'de partida': 'for this game', 'extra de cuenta': 'account extras',
    'Completadas {total} palabras': '{total} words completed', '{done} de {total} completadas': '{done} of {total} completed',
    'No se pudo validar la respuesta.': 'The answer could not be checked.', 'Respuesta correcta.': 'Correct answer.',
    '¡Sumaste {points} puntos por aprender esta palabra!': 'You earned {points} points for learning this word!',
    'Tu avance quedó guardado. Esta palabra ya sumó puntos antes.': 'Your progress was saved. This word earned points earlier.',
    'Puedes continuar con la siguiente.': 'You can continue to the next one.', 'Todavía no.': 'Not yet.',
    'La respuesta esperada era “{answer}”.': 'The expected answer was “{answer}”.',
    'No pudimos comprobar la respuesta.': 'We could not check the answer.',
    'Revisa la conexión e inténtalo nuevamente.': 'Check your connection and try again.',
    'La palabra está escrita debajo.': 'The word is written below.',
    'Acertaste {correct} de {total} palabras ({accuracy}%) en {time}.': 'You answered {correct} of {total} words correctly ({accuracy}%) in {time}.',
    'Español': 'Spanish', 'English': 'English', 'Elige la forma correspondiente en Kichwa.': 'Choose the corresponding Kichwa form.',
    'Elige el significado más preciso.': 'Choose the most precise meaning.', 'Pista': 'Hint',
    'Se descartó una opción que no corresponde a esta palabra.': 'One option that does not match this word was removed.',
    'Pronunciación: {value}': 'Pronunciation: {value}', 'Tema: {value}.': 'Topic: {value}.',
    'Escucha la palabra': 'Listen to the word', 'Reproduce la grabación y elige su significado.': 'Play the recording and choose its meaning.',
    'Escuchar la palabra en Kichwa': 'Listen to the Kichwa word', 'Escuchar despacio': 'Listen slowly',
    'Pulsa escuchar para reproducir la grabación.': 'Press listen to play the recording.',
    'Reproduciendo la grabación.': 'Playing the recording.', 'Reproduciendo más despacio.': 'Playing more slowly.',
    'No se pudo reproducir. Puedes leer la palabra como alternativa.': 'Playback failed. You can read the word instead.',
    'Grabación terminada. Puedes escucharla otra vez.': 'Recording finished. You can listen again.',
    'No se pudo cargar la grabación. Puedes leer la palabra como alternativa.': 'The recording could not be loaded. You can read the word instead.',
    'No se pudo cargar la grabación.': 'The recording could not be loaded.',
    'Puedes leer la palabra como alternativa y continuar.': 'You can read the word instead and continue.',
    'Leer la palabra como alternativa al audio': 'Read the word as an alternative to audio',
    'Se descartó una opción que no corresponde a la grabación.': 'One option that does not match the recording was removed.',
    'Escribe la palabra completa': 'Write the complete word',
    'Se reveló una letra de la palabra en Kichwa.': 'One letter of the Kichwa word was revealed.',
    'Pregunta {current} de {total}': 'Question {current} of {total}',
    'Carta sin revelar {number}': 'Hidden card {number}',
    'Observa esta pareja: {kichwa} y {meaning}.': 'Look at this pair: {kichwa} and {meaning}.',
    'Elige primero una palabra Kichwa.': 'Choose a Kichwa word first.',
    'Después selecciona su significado.': 'Then select its meaning.',
    'Se señaló una pareja bilingüe pendiente.': 'An unmatched bilingual pair was highlighted.',
    'Palabras del reto': 'Challenge words', 'Traza una línea recta.': 'Draw a straight line.',
    'Puedes buscar en horizontal, vertical o diagonal, en ambos sentidos.': 'You can search horizontally, vertically, or diagonally, in either direction.',
    'Esa línea no corresponde a una palabra pendiente.': 'That line does not match an unfound word.',
    'Prueba con otro inicio y final.': 'Try a different start and end.',
    'Fila {row}, columna {column}: {letter}': 'Row {row}, column {column}: {letter}',
    '{word} empieza en la fila {row}, columna {column}; dirección {direction}.': '{word} starts at row {row}, column {column}; direction {direction}.',
    'No hay una pista aplicable ahora.': 'No hint is available right now.',
    'Termina o cierra la selección actual y prueba con otra palabra.': 'Finish or close the current selection and try another word.',
    'Ya utilizaste la pista de esta palabra.': 'You already used the hint for this word.',
    'Continúa con otra palabra para usar una nueva pista.': 'Continue with another word to use a new hint.',
    'Pistas de partida agotadas.': 'Game hints used up.',
    'Puedes iniciar sesión o registrarte para usar dos pistas extra una sola vez por cuenta.': 'You can sign in or register to use two extra hints once per account.',
    'No hay más pistas disponibles.': 'No more hints are available.',
    'Continúa sin pista o inicia otra partida.': 'Continue without a hint or start another game.',
    'No se pudo cargar la pista.': 'The hint could not be loaded.',
}

SECONDARY_TRANSLATIONS = {
    '10 dígitos': '10 digits',
    'Acepto los términos y la política de privacidad': 'I accept the terms and privacy policy',
    'Acerca de - Diccionario Kichwa': 'About - Kichwa Dictionary',
    'Acerca del Diccionario Kichwa': 'About the Kichwa Dictionary',
    'Actualiza tu contraseña con la actual y confirma la nueva dos veces.': 'Enter your current password and confirm the new one twice.',
    'Actualizando…': 'Updating…', 'Actualizar contraseña': 'Update password',
    'Avatar': 'Avatar', 'Aún no has jugado ninguna partida': 'You have not played any games yet',
    'Biografía': 'Biography', 'Cambiar contraseña · Diccionario Kichwa': 'Change password · Kichwa Dictionary',
    'Cancelar': 'Cancel', 'Características': 'Features', 'Categorización por temas': 'Organization by topic',
    'Ciudad': 'City', 'Combina al menos 8 caracteres y evita claves comunes': 'Use at least 8 characters and avoid common passwords',
    'Comienza a jugar para ver tus estadísticas.': 'Start playing to see your statistics.',
    'Completa solo los datos que quieras compartir. Tu correo, teléfono y fecha de nacimiento no se muestran en el perfil público.': 'Only complete the details you want to share. Your email, phone number, and birth date are not shown on your public profile.',
    'Confirma tu contraseña': 'Confirm your password', 'Confirma tu contraseña actual': 'Confirm your current password',
    'Confirma tu contraseña actual para cambiar el correo.': 'Confirm your current password to change your email.',
    'Confirmar contraseña nueva': 'Confirm new password', 'Conservar mi cuenta': 'Keep my account',
    'Contacto': 'Contact', 'Contacto - Diccionario Kichwa': 'Contact - Kichwa Dictionary',
    'Contraseña actual': 'Current password', 'Contraseña actualizada': 'Password updated',
    'Contraseña actualizada | Diccionario Kichwa': 'Password updated | Kichwa Dictionary',
    'Contraseña nueva': 'New password', 'Contribuciones': 'Contributions', 'Correctas': 'Correct',
    'Correo': 'Email', 'Crea una contraseña': 'Create a password', 'Crea una contraseña nueva': 'Create a new password',
    'Crear una comunidad de hablantes y estudiantes del Kichwa': 'Build a community of Kichwa speakers and learners',
    'Cuéntanos sobre ti...': 'Tell us about yourself...',
    'Debes aceptar los términos y la política de privacidad.': 'You must accept the terms and privacy policy.',
    'Diccionario Kichwa-Español en curación continua': 'Kichwa-Spanish dictionary under continuous review',
    'Dirección': 'Address', 'Editar datos': 'Edit details',
    'Editar perfil | Diccionario Kichwa': 'Edit profile | Kichwa Dictionary',
    'El Diccionario Kichwa es una plataforma digital dedicada a preservar, promover y facilitar el aprendizaje del idioma Kichwa, una de las lenguas indígenas más importantes de América del Sur.': 'The Kichwa Dictionary is a digital platform dedicated to preserving, promoting, and supporting the learning of Kichwa, one of the most important Indigenous languages in South America.',
    'El avatar admite hasta 2 MB.': 'The avatar can be up to 2 MB.',
    'El cambio se aplica a tu cuenta sin borrar tus palabras favoritas, partidas ni progreso.': 'The change applies to your account without deleting your favorite words, games, or progress.',
    'El enlace de recuperación es temporal y solo puede utilizarse para establecer una contraseña nueva.': 'The recovery link is temporary and can only be used to set a new password.',
    'El enlace ya fue usado, ha caducado o no corresponde a una solicitud válida.': 'The link has already been used, has expired, or does not match a valid request.',
    'El teléfono debe tener exactamente 10 dígitos numéricos.': 'The phone number must contain exactly 10 digits.',
    'Elige el nombre con el que iniciarás sesión': 'Choose the username you will use to sign in',
    'Elige un nombre de usuario': 'Choose a username', 'Elige una contraseña nueva.': 'Choose a new password.',
    'Eliminando…': 'Deleting…', 'Eliminar cuenta | Diccionario Kichwa': 'Delete account | Kichwa Dictionary',
    'Eliminar definitivamente': 'Delete permanently', 'Eliminar mi cuenta': 'Delete my account',
    'Enlace no válido': 'Invalid link', 'Enviando…': 'Sending…', 'Enviar enlace': 'Send link',
    'Enviar enlace seguro': 'Send secure link',
    'Escribe el correo asociado a la cuenta. La respuesta será la misma exista o no una coincidencia.': 'Enter the email linked to the account. The response will be the same whether or not a match exists.',
    'Escribe la contraseña actual y repite la nueva para evitar errores.': 'Enter your current password and repeat the new one to avoid mistakes.',
    'Ese nombre de usuario ya está en uso.': 'That username is already in use.',
    'Esta cuenta no está disponible.': 'This account is unavailable.',
    'Facilitar el aprendizaje del idioma a través de herramientas interactivas': 'Support language learning through interactive tools',
    'Fecha': 'Date', 'Fecha de nacimiento': 'Birth date',
    'Grabaciones de pronunciación y ejemplos de uso cuando estén revisados': 'Pronunciation recordings and usage examples when reviewed',
    'Guardando…': 'Saving…', 'Guardar cambios': 'Save changes', 'Guardar contraseña': 'Save password',
    'Género': 'Gender', 'Incorrectas': 'Incorrect', 'Intentar con otro correo': 'Try another email',
    'Ir a juegos': 'Go to games', 'Juego': 'Game', 'Juegos interactivos para el aprendizaje': 'Interactive learning games',
    'La contraseña anterior ya no sirve para iniciar sesión.': 'Your previous password can no longer be used to sign in.',
    'La contraseña distingue mayúsculas y minúsculas': 'Passwords are case-sensitive',
    'La cuenta, el perfil y las relaciones guardadas en la base principal dejarán de estar disponibles.': 'The account, profile, and related records stored in the main database will no longer be available.',
    'La edad aparecerá al elegir tu fecha de nacimiento.': 'Your age will appear after you choose your birth date.',
    'La fecha de nacimiento no puede ser futura.': 'The birth date cannot be in the future.',
    'La imagen debe pesar 2 MB o menos.': 'The image must be 2 MB or smaller.',
    'La imagen no puede superar 4096 × 4096 píxeles.': 'The image cannot exceed 4096 × 4096 pixels.',
    'La respuesta no confirma si una dirección está registrada; así protegemos la privacidad de las cuentas.': 'The response does not confirm whether an address is registered; this protects account privacy.',
    'La validación final utiliza las reglas de seguridad configuradas en el servidor.': 'Final validation uses the security rules configured on the server.',
    'Mis estadísticas': 'My statistics', 'Mis estadísticas - Diccionario Kichwa': 'My statistics - Kichwa Dictionary',
    'Mostrar contraseña': 'Show password', 'Mostrar mi perfil públicamente': 'Show my profile publicly',
    'Mostrar mi usuario y puntos en el ranking público': 'Show my username and points in the public ranking',
    'Necesaria para cambiar el correo': 'Required to change your email',
    'Necesitamos tu contraseña actual para confirmar el cambio.': 'We need your current password to confirm the change.',
    'Nivel de Kichwa': 'Kichwa level',
    'No pudimos iniciar sesión con esos datos. Revisa el usuario o correo y la contraseña.': 'We could not sign you in with those details. Check your username or email and password.',
    'Nos encantaría escucharte. Si tienes preguntas sobre el diccionario, sugerencias para mejorarlo o quieres contribuir con nuevas palabras, no dudes en contactarnos.': 'We would love to hear from you. Contact us with questions about the dictionary, suggestions, or new word contributions.',
    'Nuestra misión': 'Our mission', 'Nueva contraseña': 'New password',
    'Nueva contraseña | Diccionario Kichwa': 'New password | Kichwa Dictionary', 'Objetivos': 'Goals',
    'Opcional y privado. Escribe exactamente 10 dígitos, sin espacios ni símbolos.': 'Optional and private. Enter exactly 10 digits without spaces or symbols.',
    'Opcional. Puedes dejar de aparecer desmarcando esta opción cuando quieras.': 'Optional. You can leave the ranking at any time by clearing this option.',
    'Partidas jugadas': 'Games played', 'País': 'Country',
    'Perfil público y ranking son opciones independientes.': 'Public profile and ranking are independent options.',
    'Preservar el vocabulario y la riqueza lingüística del Kichwa': 'Preserve Kichwa vocabulary and linguistic richness',
    'Promover la cultura y tradiciones asociadas al idioma Kichwa': 'Promote the culture and traditions associated with Kichwa',
    'Puedes usar tu nombre de usuario o el correo asociado': 'You can use your username or linked email',
    'Puntos totales': 'Total points', 'Puntuación': 'Score',
    'Quiero recibir novedades educativas por correo': 'I want to receive educational updates by email',
    'Recibir novedades educativas por correo': 'Receive educational updates by email',
    'Recupera el acceso con calma.': 'Recover access with confidence.',
    'Recuperar acceso | Diccionario Kichwa': 'Recover access | Kichwa Dictionary',
    'Repite exactamente la contraseña anterior': 'Repeat the previous password exactly',
    'Repite la contraseña': 'Repeat the password', 'Repite la contraseña nueva': 'Repeat the new password',
    'Revisa antes de eliminar.': 'Review before deleting.', 'Revisa tu correo | Diccionario Kichwa': 'Check your email | Kichwa Dictionary',
    'Revisa tu correo.': 'Check your email.',
    'Se eliminarán el perfil, favoritas y estadísticas vinculadas. Las copias de seguridad dependen de la política del operador.': 'The linked profile, favorites, and statistics will be deleted. Backups depend on the operator policy.',
    'Seguridad de la cuenta': 'Account security',
    'Si eres hablante de Kichwa o tienes conocimientos del idioma, tu contribución es muy valiosa para enriquecer nuestro diccionario.': 'If you speak Kichwa or know the language, your contribution is very valuable for enriching our dictionary.',
    'Si existe una cuenta activa con ese correo, recibirás un enlace temporal. Revisa también la carpeta de correo no deseado.': 'If an active account uses that email, you will receive a temporary link. Check your spam folder as well.',
    'Sistema de favoritos personalizado': 'Personal favorite words', 'Solicitar otro enlace': 'Request another link',
    'Solicitud recibida': 'Request received', 'Solo 10 números; este dato es privado.': 'Exactly 10 digits; this information is private.',
    'Teléfono': 'Phone', 'Tu acceso está listo.': 'Your access is ready.', 'Tu apellido': 'Your last name',
    'Tu contraseña': 'Your password',
    'Tu información de contacto permanece privada. Para cambiar el correo, confirma tu contraseña actual.': 'Your contact information remains private. To change your email, confirm your current password.',
    'Tu nombre': 'Your first name', 'Tu perfil, bajo tu control.': 'Your profile, under your control.',
    'Tu usuario o correo': 'Your username or email',
    'Una clave segura para seguir aprendiendo.': 'A secure password for continued learning.',
    'Usa al menos 8 caracteres y evita contraseñas comunes.': 'Use at least 8 characters and avoid common passwords.',
    'Usa solo letras y espacios.': 'Use letters and spaces only.',
    'Usa solo letras y espacios; puedes incluir tildes': 'Use letters and spaces only; accented letters are allowed',
    'Usa una contraseña única y difícil de adivinar.': 'Use a unique password that is difficult to guess.',
    'Usa una frase única que no compartas con otros servicios.': 'Use a unique phrase that you do not share with other services.',
    'Usaremos este correo para recuperar el acceso a tu cuenta': 'We will use this email to recover access to your account',
    'Volver a iniciar sesión': 'Return to sign in', 'Volver al perfil': 'Return to profile',
    'Ya existe una cuenta registrada con este correo.': 'An account is already registered with this email.',
    'Ya puedes volver al diccionario usando tu nueva contraseña.': 'You can now return to the dictionary using your new password.',
    '¿Tienes preguntas o sugerencias?': 'Do you have questions or suggestions?',
    'Últimas partidas': 'Recent games',
    'Restablece tu contraseña de Diccionario Kichwa': 'Reset your Kichwa Dictionary password',
    'Has solicitado restablecer la contraseña de tu cuenta en Diccionario Kichwa.': 'You requested a password reset for your Kichwa Dictionary account.',
    'Abre este enlace para crear una nueva contraseña:': 'Open this link to create a new password:',
    'Si no solicitaste este cambio, puedes ignorar este correo.': 'If you did not request this change, you can ignore this email.',
    'Bienvenido al Diccionario Kichwa': 'Welcome to the Kichwa Dictionary',
    '¡Bienvenido al Diccionario Kichwa!': 'Welcome to the Kichwa Dictionary!',
    'Preservando y compartiendo la riqueza cultural del idioma Kichwa': 'Preserving and sharing the cultural richness of the Kichwa language',
    'Nos alegra tenerte en nuestra comunidad. Has dado el primer paso para explorar y aprender uno de los idiomas más ricos y antiguos de América.': 'We are glad to welcome you to our community. You have taken the first step toward exploring and learning one of the richest and oldest languages in the Americas.',
    '¿Qué puedes hacer ahora?': 'What can you do now?',
    'Explora el diccionario y busca palabras en Kichwa, español o inglés.': 'Explore the dictionary and search for words in Kichwa, Spanish, or English.',
    'Practica con nuestros juegos educativos.': 'Practice with our educational games.',
    'Guarda las palabras que más te interesen.': 'Save the words that interest you most.',
    'Sigue tu progreso de aprendizaje.': 'Track your learning progress.',
    'Nuestro diccionario es un puente hacia la comprensión de una cultura milenaria. Cada palabra que aprendes te acerca a la sabiduría de los pueblos Kichwa.': 'Our dictionary is a bridge to understanding an ancient culture. Every word you learn brings you closer to the knowledge of Kichwa peoples.',
    'Comenzar a explorar': 'Start exploring',
    'Si tienes alguna pregunta, no dudes en contactarnos.': 'If you have any questions, please contact us.',
    'Equipo del Diccionario Kichwa': 'Kichwa Dictionary Team',
    'Hola %(name)s,': 'Hello %(name)s,',
    'Muestra solo palabras del tema seleccionado': 'Show only words from the selected topic',
    'Filtra según la complejidad de pronunciación': 'Filter by pronunciation complexity',
    'Una entrada para comenzar': 'An entry to get started',
    'Del %(start)s al %(end)s': 'From %(start)s to %(end)s',
    'Avance privado del reto semanal: %(avance)s de %(meta)s palabras': 'Private weekly challenge progress: %(avance)s of %(meta)s words',
    'Explorar %(total)s palabras de %(category)s': 'Explore %(total)s words in %(category)s',
    'No hay temas disponibles todavía.': 'No topics are available yet.',
    'Aún no hay participantes en el ranking. La práctica puede comenzar hoy.': 'There are no ranking participants yet. Practice can start today.',
    'Activar o desactivar tu participación en el ranking': 'Enable or disable your ranking participation',
    'Gestionar mi participación': 'Manage my participation', 'Unirme al ranking': 'Join the ranking',
    'Todavía no hay búsquedas exactas esta semana. Prueba con una palabra en Kichwa, español o inglés.': 'There are no exact searches this week yet. Try a word in Kichwa, Spanish, or English.',
    'Volver al inicio del diccionario': 'Return to the dictionary home page',
    'Abrir menú de navegación': 'Open navigation menu', 'Ir a la portada': 'Go to the home page',
    'Buscar en Kichwa, español e inglés': 'Search in Kichwa, Spanish, and English',
    'Practicar vocabulario con juegos': 'Practice vocabulary with games',
    'Abrir opciones de tu cuenta': 'Open your account options',
    'Acceder a tu progreso guardado': 'Access your saved progress',
    'Crear una cuenta de aprendizaje': 'Create a learning account',
    'Volver al inicio sin acceder a una cuenta': 'Return home without signing in',
    'Beneficios de la cuenta': 'Account benefits', 'Comprobando…': 'Checking…',
    'Mostrar u ocultar la contraseña escrita': 'Show or hide the entered password',
    'Comprobar tus datos y abrir la cuenta': 'Check your details and open the account',
    'Compromisos del registro': 'Registration commitments',
    'Mostrar u ocultar la contraseña': 'Show or hide the password',
    'Mostrar u ocultar la confirmación': 'Show or hide the confirmation',
    'Creando cuenta…': 'Creating account…', 'Validar los datos y crear tu cuenta': 'Validate the details and create your account',
    'Ver todos los temas y cuántas palabras contienen': 'View all topics and their word counts',
    'Filtra por complejidad de pronunciación': 'Filter by pronunciation complexity',
    'Filtros activos': 'Active filters', 'Ver fotografía de %(author)s en Pexels': 'View photograph by %(author)s on Pexels',
    'Foto en Pexels': 'Photo on Pexels', 'Páginas de resultados': 'Result pages',
    'Filtrar historial': 'Filter history', 'Páginas del historial': 'History pages',
    'Contenido del perfil': 'Profile content', 'Avance hacia el nivel %(level)s': 'Progress toward level %(level)s',
    'Herramientas de tu cuenta': 'Your account tools', 'Ruta de navegación': 'Breadcrumb',
    'Diccionario': 'Dictionary', 'Tu navegador no admite la reproducción de audio.': 'Your browser does not support audio playback.',
    'Contenido de la entrada': 'Entry content', 'Fotografía de': 'Photograph by', 'en': 'on',
    'Datos y acciones de la entrada': 'Entry details and actions', 'Acciones para continuar': 'Actions to continue',
    'Resumen de aprendizaje': 'Learning summary', 'Preferencias para empezar': 'Starting preferences',
    'Configurar esta práctica': 'Configure this practice', 'Ver entrada de %(word)s': 'View entry for %(word)s',
    'Quitar %(word)s de favoritas': 'Remove %(word)s from favorites', 'Quitar': 'Remove',
    'Páginas de favoritas': 'Favorite pages', 'Páginas de %(category)s': '%(category)s pages',
    'Traducción': 'Translation', 'Completar palabras': 'Complete words',
    'Juego de memoria': 'Memory game', 'Conectar traducciones': 'Match translations',
    'Sopa de letras': 'Word search', 'Búsqueda': 'Search',
    'Palabra consultada': 'Entry viewed', 'Partida terminada': 'Game completed',
    'Principiante': 'Beginner', 'Intermedio': 'Intermediate', 'Avanzado': 'Advanced', 'Nativo': 'Native',
    'Masculino': 'Male', 'Femenino': 'Female', 'Otro': 'Other',
    'Buscaste “%(term)s”': 'You searched for “%(term)s”',
    'Viste %(word)s': 'You viewed %(word)s', 'Jugaste %(game)s': 'You played %(game)s',
}

TRANSLATIONS.update(SECONDARY_TRANSLATIONS)

PLURALS = {
    ('%(total)s resultado', '%(total)s resultados'): ('%(total)s result', '%(total)s results'),
    ('%(total)s palabra', '%(total)s palabras'): ('%(total)s word', '%(total)s words'),
    ('%(total)s consulta', '%(total)s consultas'): ('%(total)s search', '%(total)s searches'),
    ('Edad actual: %(edad_actual)s año', 'Edad actual: %(edad_actual)s años'): ('Current age: %(edad_actual)s year', 'Current age: %(edad_actual)s years'),
}


def _mo_bytes(messages):
    catalog = {'': 'Content-Type: text/plain; charset=UTF-8\nLanguage: en\nPlural-Forms: nplurals=2; plural=(n != 1);\n'}
    catalog.update(TRANSLATIONS)
    for (singular, plural), (translated_singular, translated_plural) in PLURALS.items():
        catalog[f'{singular}\0{plural}'] = f'{translated_singular}\0{translated_plural}'
    encoded = sorted((key.encode(), value.encode()) for key, value in catalog.items())
    count = len(encoded)
    ids_offset = 7 * 4 + count * 16
    ids = b''.join(key + b'\0' for key, _ in encoded)
    strings_offset = ids_offset + len(ids)
    strings = b''.join(value + b'\0' for _, value in encoded)
    offsets = []
    cursor = ids_offset
    for key, _ in encoded:
        offsets.append((len(key), cursor))
        cursor += len(key) + 1
    translations = []
    cursor = strings_offset
    for _, value in encoded:
        translations.append((len(value), cursor))
        cursor += len(value) + 1
    header = struct.pack('<7I', 0x950412DE, 0, count, 28, 28 + count * 8, 0, 0)
    tables = b''.join(struct.pack('<2I', *item) for item in offsets + translations)
    return header + tables + ids + strings


def _po_text():
    lines = [
        'msgid ""', 'msgstr ""',
        '"Content-Type: text/plain; charset=UTF-8\\n"',
        '"Language: en\\n"',
        '"Plural-Forms: nplurals=2; plural=(n != 1);\\n"', '',
    ]
    for msgid, msgstr in sorted(TRANSLATIONS.items()):
        lines.extend((f'msgid {json.dumps(msgid, ensure_ascii=False)}', f'msgstr {json.dumps(msgstr, ensure_ascii=False)}', ''))
    for (singular, plural), (translated_singular, translated_plural) in sorted(PLURALS.items()):
        lines.extend((
            f'msgid {json.dumps(singular, ensure_ascii=False)}',
            f'msgid_plural {json.dumps(plural, ensure_ascii=False)}',
            f'msgstr[0] {json.dumps(translated_singular, ensure_ascii=False)}',
            f'msgstr[1] {json.dumps(translated_plural, ensure_ascii=False)}', '',
        ))
    return '\n'.join(lines)


def main():
    target = Path(__file__).resolve().parents[1] / 'locale' / 'en' / 'LC_MESSAGES'
    target.mkdir(parents=True, exist_ok=True)
    (target / 'django.po').write_text(_po_text(), encoding='utf-8', newline='\n')
    (target / 'django.mo').write_bytes(_mo_bytes(TRANSLATIONS))
    print(f'Catálogo inglés generado: {len(TRANSLATIONS)} textos y {len(PLURALS)} plurales.')


if __name__ == '__main__':
    main()
